const copy = {
  en: {
    hero: {
      eyebrow: "Time, made visible",
      title: "Time is the one asset you cannot earn back.",
      subtitle: "Understand how much has passed, how much you still have, and what is still yours to shape.",
      birthday: "Your birthday",
      expectedLifespan: "Expected lifespan",
      currentAge: "Current age",
      daysLeft: "Days left",
      weeksLeft: "Weeks left",
      warning: "Increase expected lifespan to see remaining time beyond your current age.",
      cta: "Understand your time",
    },
    grid: {
      eyebrow: "Your weeks",
      title: "{value}% of your expected life is already behind you.",
      body:
        "Each row is one year of your life. The filled marks are behind you; the open marks are the time still ahead.",
      now: "The highlighted mark is the moment you are living now.",
      calendarTitle: "Your calendar years",
      slotsPerYear: "54 slots per year",
      emptySlot: "Empty slot",
      prediction: "Prediction",
      noEvent: "No major event in this dataset.",
      bodyFallback: "Physiology keeps changing with age.",
      tooltip: "Year {year}, slot {slot} of 54, age {age}, {state} | Body: {body} | World: {world}",
    },
    time: {
      eyebrow: "Time compression",
      title: "Not every remaining day is truly available.",
      body: "Sleep, work, screens, errands, and obligations will claim much of what appears to be ahead.",
      labels: {
        sleepDays: "Sleeping",
        workDays: "Working",
        screenDays: "Screen time",
        obligationDays: "Obligations",
        meaningfulDays: "Truly yours",
      },
      days: "{value} days",
      emphasis: "The sharper question is not how many days remain. It is how many can still be lived deliberately.",
    },
    mortality: {
      eyebrow: "Mortality reality",
      title: "Aging is not the only threat. Accumulation is.",
      lead: "For most people, the danger is chronic disease building quietly, long before it becomes visible.",
      body:
        "Heart disease, cancer, stroke, diabetes, dementia, and respiratory disease rarely arrive out of nowhere. They are long processes shaped over years.",
      exploreRisk: "Explore mortality risk",
      chronic: "Understand chronic disease",
      overview: "See risk overview",
    },
    actions: {
      eyebrow: "Agency",
      title: "The trajectory is not fixed.",
      subtitle: "The point is not simply more years. It is more capable years, with more of yourself intact.",
      cards: [
        ["Z2", "Build your aerobic base", "Zone 2 training improves cardiovascular fitness and supports long-term metabolic health.", "Learn why Zone 2 matters"],
        ["ST", "Keep your strength", "Muscle is a reserve of independence. Losing it makes the world smaller.", "See strength actions"],
        ["SL", "Protect recovery", "Sleep shapes energy, metabolism, cognition, hormones, and long-term resilience.", "Improve recovery"],
        ["MH", "Control the slow burn", "Blood sugar, blood pressure, lipids, and inflammation quietly shape risk for decades.", "Start with lifestyle"],
      ],
    },
    final: {
      title: "Life is urgent. Life is now.",
      subtitle: "Do not wait for the body to force a decision you can make earlier.",
      primary: "Start changing the trajectory",
      secondary: "Study what actually kills us",
    },
    note: "Current model: age {age} with expected lifespan {expected}. Inputs are bounded between 0 and 120 so remaining time never becomes negative.",
  },
  zh: {
    hero: {
      eyebrow: "让时间被看见",
      title: "寸阴不可再得。",
      subtitle: "看清已逝之日、当下所持之时，以及仍可亲手改写的余地。",
      birthday: "你的生日",
      expectedLifespan: "预期寿命",
      currentAge: "当前年龄",
      daysLeft: "剩余天数",
      weeksLeft: "剩余周数",
      warning: "请提高预期寿命，才能看到超过当前年龄之后的剩余时间。",
      cta: "看见你所拥有的时间",
    },
    grid: {
      eyebrow: "你的每一周",
      title: "按当前假设，你的一生已有 {value}% 成为往日。",
      body: "每一行，是人生的一年。亮起的格子已经走过，尚未亮起的，仍在前方。",
      now: "被高亮的这一格，正是此刻。",
      calendarTitle: "你的自然年",
      slotsPerYear: "每年 54 格",
      emptySlot: "空格",
      prediction: "预测",
      noEvent: "这个数据集中没有对应的大事件。",
      bodyFallback: "身体仍在随年龄变化。",
      tooltip: "{year} 年，第 {slot}/54 格，年龄 {age}，{state} | 身体：{body} | 世界：{world}",
    },
    time: {
      eyebrow: "时间压缩",
      title: "余日虽在，并非日日可由己。",
      body: "睡眠、工作、屏幕、奔波、琐事与责任，都会分走那些看似还在前方的日子。",
      labels: {
        sleepDays: "睡眠",
        workDays: "工作",
        screenDays: "屏幕时间",
        obligationDays: "日常责任",
      meaningfulDays: "可由己用",
      },
      days: "{value} 天",
      emphasis: "真正要问的，不只是还剩多少日子，而是还有多少日子能清醒、自主地活。",
    },
    mortality: {
      eyebrow: "死亡现实",
      title: "可畏的往往不是年岁，而是积习。",
      lead: "对多数人来说，真正的风险在显露之前，已经悄然累积多年。",
      body: "心脏病、癌症、中风、糖尿病、痴呆和呼吸系统疾病，很少是临终前忽然降下的意外。它们多半是长年轨迹汇成的结果。",
      exploreRisk: "探索死亡风险",
      chronic: "理解慢性病",
      overview: "查看风险总览",
    },
    actions: {
      eyebrow: "行动感",
      title: "轨迹未定，仍可转圜。",
      subtitle: "所求不只是多活几年，而是在更多年里保有体力、清明与自主。",
      cards: [
        ["Z2", "建立有氧基础", "Zone 2 训练能改善心肺能力，并支持长期代谢健康。", "了解 Zone 2 为什么重要"],
        ["ST", "守住力量", "肌肉是独立生活的底气。失去它，天地会一点点变窄。", "查看力量行动"],
        ["SL", "护住恢复", "睡眠关乎精力、代谢、认知、激素，也关乎长期韧性。", "改善恢复"],
        ["MH", "管住慢火", "血糖、血压、血脂与炎症，会在数十年里暗暗塑造风险。", "从生活方式开始"],
      ],
    },
    final: {
      title: "Life is urgent. Life is now.",
      subtitle: "不要等身体替你作主，才想起换一种活法。",
      primary: "从今天改写轨迹",
      secondary: "看清真正夺走生命的东西",
    },
    note: "当前模型：年龄 {age}，预期寿命 {expected}。输入会限制在 0 到 120 之间，确保剩余时间不会变成负数。",
  },
};

copy.fr = {
  ...copy.en,
  hero: {
    eyebrow: "Le temps rendu visible",
    title: "Le temps est le seul actif que vous ne pouvez pas regagner.",
    subtitle: "Comprenez ce qui est passe, le temps que vous avez encore, et ce que vous pouvez encore faconner.",
    birthday: "Votre date de naissance",
    expectedLifespan: "Esperance de vie",
    currentAge: "Age actuel",
    daysLeft: "Jours restants",
    weeksLeft: "Semaines restantes",
    warning: "Augmentez l'esperance de vie pour voir le temps restant au-dela de votre age actuel.",
    cta: "Comprendre votre temps",
  },
  grid: {
    ...copy.en.grid,
    eyebrow: "Vos semaines",
    title: "{value}% de votre vie attendue est deja derriere vous.",
    body:
      "Chaque ligne represente une annee de votre vie. Les marques remplies sont derriere vous; les autres sont le temps encore devant vous.",
    now: "La marque mise en lumiere est le moment que vous vivez maintenant.",
    calendarTitle: "Vos annees civiles",
    slotsPerYear: "54 cases par an",
    emptySlot: "Case vide",
    prediction: "Prediction",
    noEvent: "Aucun evenement majeur dans ce jeu de donnees.",
    bodyFallback: "La physiologie continue de changer avec l'age.",
    tooltip: "Annee {year}, case {slot}/54, age {age}, {state} | Corps: {body} | Monde: {world}",
  },
  time: {
    ...copy.en.time,
    eyebrow: "Compression du temps",
    title: "Tous les jours restants ne sont pas vraiment disponibles.",
    body: "Le sommeil, le travail, les ecrans, les courses et les obligations prendront une grande part de ce qui semble encore devant vous.",
    labels: {
      sleepDays: "Sommeil",
      workDays: "Travail",
      screenDays: "Ecrans",
      obligationDays: "Obligations",
      meaningfulDays: "Vraiment a vous",
    },
    days: "{value} jours",
    emphasis: "La vraie question n'est pas combien de jours restent. C'est combien peuvent encore etre vecus deliberement.",
  },
  mortality: {
    ...copy.en.mortality,
    eyebrow: "Realite de la mortalite",
    title: "Le risque n'est pas seulement l'age. C'est l'accumulation.",
    lead: "Pour la plupart des gens, le danger se construit en silence, longtemps avant de devenir visible.",
    body:
      "Maladies cardiaques, cancer, AVC, diabete, demence et maladies respiratoires apparaissent rarement de nulle part. Ce sont des processus longs, faconnes par les annees.",
    exploreRisk: "Explorer le risque de mortalite",
    chronic: "Comprendre les maladies chroniques",
    overview: "Voir la vue d'ensemble",
  },
  actions: {
    ...copy.en.actions,
    eyebrow: "Marge d'action",
    title: "La trajectoire n'est pas fixe.",
    subtitle: "Il ne s'agit pas seulement d'ajouter des annees. Il s'agit de garder plus longtemps capacite, clarte et autonomie.",
  },
  final: {
    title: "Life is urgent. Life is now.",
    subtitle: "N'attendez pas que le corps vous impose une decision que vous pouvez prendre plus tot.",
    primary: "Commencer a changer la trajectoire",
    secondary: "Comprendre ce qui nous tue vraiment",
  },
  note: "Modele actuel: age {age}, esperance de vie {expected}. Les entrees sont limitees entre 0 et 120 pour eviter un temps restant negatif.",
};

copy.es = {
  ...copy.en,
  hero: {
    eyebrow: "El tiempo visible",
    title: "El tiempo es el unico activo que no puedes recuperar.",
    subtitle: "Entiende cuanto ha pasado, cuanto tiempo tienes todavia y que puedes seguir moldeando.",
    birthday: "Tu fecha de nacimiento",
    expectedLifespan: "Esperanza de vida",
    currentAge: "Edad actual",
    daysLeft: "Dias restantes",
    weeksLeft: "Semanas restantes",
    warning: "Aumenta la esperanza de vida para ver el tiempo restante mas alla de tu edad actual.",
    cta: "Entender tu tiempo",
  },
  grid: {
    ...copy.en.grid,
    eyebrow: "Tus semanas",
    title: "El {value}% de tu vida esperada ya quedo atras.",
    body:
      "Cada fila representa un ano de tu vida. Las marcas llenas ya quedaron atras; las abiertas son el tiempo que todavia queda.",
    now: "La marca resaltada es el momento que estas viviendo ahora.",
    calendarTitle: "Tus anos calendario",
    slotsPerYear: "54 casillas por ano",
    emptySlot: "Casilla vacia",
    prediction: "Prediccion",
    noEvent: "No hay un evento importante en este conjunto de datos.",
    bodyFallback: "La fisiologia sigue cambiando con la edad.",
    tooltip: "Ano {year}, casilla {slot}/54, edad {age}, {state} | Cuerpo: {body} | Mundo: {world}",
  },
  time: {
    ...copy.en.time,
    eyebrow: "Compresion del tiempo",
    title: "No todos los dias restantes estan realmente disponibles.",
    body: "Dormir, trabajar, pantallas, recados y obligaciones reclamaran gran parte de lo que parece estar por delante.",
    labels: {
      sleepDays: "Dormir",
      workDays: "Trabajo",
      screenDays: "Pantallas",
      obligationDays: "Obligaciones",
      meaningfulDays: "Realmente tuyos",
    },
    days: "{value} dias",
    emphasis: "La pregunta mas clara no es cuantos dias quedan. Es cuantos todavia pueden vivirse con intencion.",
  },
  mortality: {
    ...copy.en.mortality,
    eyebrow: "Realidad de mortalidad",
    title: "La amenaza no es solo la edad. Es la acumulacion.",
    lead: "Para la mayoria, el peligro se construye en silencio mucho antes de hacerse visible.",
    body:
      "Enfermedad cardiaca, cancer, accidente cerebrovascular, diabetes, demencia y enfermedad respiratoria rara vez aparecen de la nada. Son procesos largos, moldeados durante anos.",
    exploreRisk: "Explorar riesgo de mortalidad",
    chronic: "Entender enfermedad cronica",
    overview: "Ver resumen de riesgos",
  },
  actions: {
    ...copy.en.actions,
    eyebrow: "Agencia",
    title: "La trayectoria no esta fija.",
    subtitle: "No se trata solo de sumar anos. Se trata de conservar capacidad, claridad y autonomia durante mas tiempo.",
  },
  final: {
    title: "Life is urgent. Life is now.",
    subtitle: "No esperes a que el cuerpo te obligue a tomar una decision que puedes tomar antes.",
    primary: "Empezar a cambiar la trayectoria",
    secondary: "Entender lo que realmente nos mata",
  },
  note: "Modelo actual: edad {age}, esperanza de vida {expected}. Las entradas se limitan entre 0 y 120 para que el tiempo restante nunca sea negativo.",
};

export function getLifeCopy(locale) {
  return copy[locale] || copy.en;
}
