const bodyDevelopmentFacts = {
    0: "Newborns weigh about 3.2 kg on average, head circumference ~35 cm.",
    1: "First teeth emerge, walking begins, brain reaches 60% of adult size.",
    2: "Rapid language development, peak synaptic connections in the brain.",
    3: "Immune system matures, improved motor coordination, running ability.",
    4: "Full set of baby teeth, vision nearly at adult levels.",
    5: "Increased physical strength, bones grow rapidly.",
    6: "First permanent molars appear, cognitive abilities expand.",
    7: "Logical reasoning improves, hand-eye coordination strengthens.",
    8: "Growth slows slightly, fine motor skills continue developing.",
    9: "Improved memory and concentration, more complex muscle coordination.",
    10: "Brain reaches about 90% of adult size, continued cognitive refinement.",
    
    11: "Start of puberty in some children, increased hormone production.",
    12: "Bone growth accelerates, muscle mass increases.",
    13: "Peak height velocity for girls, voice changes begin in boys.",
    14: "Increased lung capacity, improved athletic performance.",
    15: "Peak height velocity for boys, muscle strength continues increasing.",
    16: "Reaction time peaks, stronger cardiovascular endurance.",
    17: "Bone density strengthens, cognitive reasoning improves.",
    18: "Most organs fully developed, skin more resilient.",
    19: "Metabolism starts slowing slightly, muscle recovery still quick.",
    20: "Physical performance peaks in endurance and strength.",

    21: "Brain reaches full maturity, decision-making abilities solidify.",
    22: "Maximum lung function, cardiovascular efficiency peaks.",
    23: "Peak bone mass achieved, muscles are at their strongest.",
    24: "Reaction time and agility at their highest levels.",
    25: "Prefrontal cortex fully developed, best age for cognitive sharpness.",
    26: "Tendon and ligament elasticity begin to decline slightly.",
    27: "Aerobic capacity starts a slow decline if not maintained.",
    28: "Strength remains high but recovery takes slightly longer.",
    29: "Peak age for high-intensity physical performance.",
    30: "Metabolism begins to slow, muscle mass maintenance becomes important.",

    31: "Collagen production decreases, early signs of skin aging.",
    32: "Endurance remains strong, but peak strength slightly declines.",
    33: "Cardiovascular efficiency starts to gradually decline.",
    34: "Flexibility reduces, injury risk increases without proper care.",
    35: "Cognitive speed and memory begin to decline slowly.",
    36: "Muscle mass reduction begins without resistance training.",
    37: "Recovery time increases after strenuous activities.",
    38: "Joint stiffness becomes more noticeable.",
    39: "First significant signs of age-related vision decline.",
    40: "Muscle loss accelerates without exercise, metabolism slows further.",

    41: "Increased risk of high blood pressure and cholesterol issues.",
    42: "Reaction time slows, endurance needs more training to maintain.",
    43: "Skin elasticity decreases, wrinkles become more visible.",
    44: "Hearing loss begins in some individuals.",
    45: "Higher risk of heart disease, bone density starts declining.",
    46: "Hormonal changes cause muscle loss and fat gain.",
    47: "Risk of osteoporosis increases, cartilage in joints wears down.",
    48: "Immune function weakens slightly, increased susceptibility to infections.",
    49: "Memory recall declines, brain processing speed slows.",
    50: "Menopause for most women, significant bone density loss begins.",

    51: "Arthritis becomes more common, joint pain increases.",
    52: "Greater difficulty in maintaining muscle mass without strength training.",
    53: "Cardiovascular endurance continues to decrease.",
    54: "Vision problems, including presbyopia, are common.",
    55: "Increased risk of diabetes, metabolic syndrome more prevalent.",
    56: "Hormonal changes lead to further muscle and collagen loss.",
    57: "Higher risk of Alzheimer’s and other cognitive disorders.",
    58: "Liver function declines slightly, affecting alcohol metabolism.",
    59: "Exercise recovery time significantly longer.",
    60: "Loss of balance and coordination increases fall risks.",

    61: "Hearing loss becomes more pronounced.",
    62: "Metabolism slows significantly, weight gain common.",
    63: "Greater reliance on medication for chronic conditions.",
    64: "Tendon stiffness and reduced flexibility.",
    65: "Immune system response slows, increased risk of infection.",
    66: "Loss of muscle coordination, reaction times continue slowing.",
    67: "Bone fractures become more likely after falls.",
    68: "Significant decline in cardiovascular efficiency.",
    69: "Deep sleep duration reduces, leading to sleep disturbances.",
    70: "Increased risk of neurodegenerative diseases like dementia.",

    71: "Significant loss of lean body mass.",
    72: "Memory retention and processing speed decline further.",
    73: "High risk of heart disease and stroke.",
    74: "Skin becomes thinner, bruising more common.",
    75: "Significant decrease in physical endurance.",
    76: "Increased reliance on mobility aids.",
    77: "Digestive efficiency reduces, nutrient absorption declines.",
    78: "Greater difficulty in thermoregulation, sensitivity to cold.",
    79: "Chronic pain conditions more prevalent.",
    80: "Cognitive decline more noticeable, risk of dementia high.",

    81: "Increased frailty, walking speed decreases.",
    82: "Immune system weakens, making infections dangerous.",
    83: "Swallowing difficulties may appear.",
    84: "Muscle atrophy accelerates, affecting mobility.",
    85: "Significant dependence on caregivers for daily activities.",
    86: "Bones become extremely brittle, fractures can be fatal.",
    87: "Height loss due to spinal compression increases.",
    88: "Risk of pneumonia and respiratory issues rises.",
    89: "Nerve function declines, reducing sensitivity in extremities.",
    90: "Severe loss of independence in daily life.",

    91: "Cardiac output is significantly lower, fatigue sets in faster.",
    92: "Memory recall is significantly reduced.",
    93: "Increased reliance on assistive devices for mobility.",
    94: "Digestion slows dramatically, leading to nutrient deficiencies.",
    95: "High risk of falls, often resulting in serious injuries.",
    96: "Body fat redistribution leads to frailty.",
    97: "Respiratory function severely compromised.",
    98: "Severe loss of hearing and vision.",
    99: "Brain function is significantly impaired in most individuals.",
    100: "Very limited mobility, full-time care often required.",

    101: "Surpassing 100 is rare, but some individuals remain independent.",
    102: "Extreme longevity cases usually require specialized care.",
    103: "Body mass reduces further, bones extremely fragile.",
    104: "Cognitive abilities almost entirely dependent on genetics.",
    105: "Cardiovascular efficiency barely supports daily activity.",
    106: "Nutrition absorption is highly inefficient.",
    107: "Even minor illnesses pose a significant threat.",
    108: "Severe muscle degeneration leads to near-total immobility.",
    109: "Almost complete loss of sensory perception.",
    110: "The few who reach this age rely entirely on caregivers.",

    111: "Mental function fluctuates significantly.",
    112: "Heart function barely sustains bodily needs.",
    113: "Muscle control almost completely lost.",
    114: "Extreme frailty, bones as fragile as glass.",
    115: "Only a handful of people reach this age worldwide.",
    116: "Severe memory loss and cognitive decline.",
    117: "Dependence on artificial life support likely.",
    118: "Body struggles to maintain basic homeostasis.",
    119: "Few recorded cases, but extreme genetic longevity possible.",
    120: "Reaching this age is an extraordinary rarity."
};

export default bodyDevelopmentFacts;