import { normalizeLocale } from "./i18n/config";

const englishFacts = {
  0: "Newborns weigh about 3.2 kg on average, with head circumference near 35 cm.",
  1: "First teeth emerge, walking begins, and the brain reaches about 60% of adult size.",
  2: "Language develops rapidly and synaptic density remains extremely high.",
  3: "The immune system matures and motor coordination improves.",
  4: "The full set of baby teeth is present and vision is near adult levels.",
  5: "Physical strength rises and bones continue rapid growth.",
  6: "The first permanent molars appear and cognitive abilities expand.",
  7: "Logical reasoning and hand-eye coordination improve.",
  8: "Growth slows slightly while fine motor skills keep developing.",
  9: "Memory, concentration, and complex muscle coordination improve.",
  10: "The brain is near 90% of adult size and cognition keeps refining.",
  11: "Puberty begins for some children and hormone production rises.",
  12: "Bone growth accelerates and muscle mass increases.",
  13: "Girls often reach peak height velocity while voice change begins for many boys.",
  14: "Lung capacity increases and athletic performance often improves.",
  15: "Many boys reach peak height velocity and muscle strength keeps climbing.",
  16: "Reaction time peaks and cardiovascular endurance is strong.",
  17: "Bone density strengthens and reasoning becomes more stable.",
  18: "Most organs are fully developed and skin is more resilient.",
  19: "Metabolism begins to slow slightly, though recovery remains quick.",
  20: "Physical performance is often near peak for endurance and strength.",
  21: "The brain reaches full maturity and decision-making stabilizes.",
  22: "Lung function and cardiovascular efficiency are near their best.",
  23: "Peak bone mass is typically achieved and muscles remain strong.",
  24: "Reaction time and agility are often at their highest.",
  25: "The prefrontal cortex is fully developed and cognition is sharp.",
  26: "Tendon and ligament elasticity starts a slow decline.",
  27: "Aerobic capacity begins a gradual decline if not trained.",
  28: "Strength remains high, though recovery may take slightly longer.",
  29: "High-intensity physical performance is still near its peak.",
  30: "Metabolism slows and preserving muscle mass becomes more important.",
  31: "Collagen production decreases and early skin aging appears.",
  32: "Endurance remains strong, though peak strength softens slightly.",
  33: "Cardiovascular efficiency begins a gradual decline.",
  34: "Flexibility decreases and injury risk rises without care.",
  35: "Cognitive speed and memory can begin a slow decline.",
  36: "Muscle loss begins without regular resistance training.",
  37: "Recovery time after hard effort gets longer.",
  38: "Joint stiffness becomes more noticeable.",
  39: "The first clear signs of age-related vision decline often appear.",
  40: "Muscle loss accelerates without exercise and metabolism slows further.",
  41: "Risk of high blood pressure and cholesterol issues increases.",
  42: "Reaction time slows and endurance needs more training to maintain.",
  43: "Skin elasticity decreases and wrinkles become more visible.",
  44: "Hearing loss begins for some people.",
  45: "Risk of heart disease rises and bone density starts declining.",
  46: "Hormonal changes can increase muscle loss and fat gain.",
  47: "Osteoporosis risk rises and joint cartilage wears down.",
  48: "Immune function weakens slightly and infection risk climbs.",
  49: "Memory recall and processing speed may decline.",
  50: "Menopause occurs for many women and bone density loss accelerates.",
  51: "Arthritis becomes more common and joint pain rises.",
  52: "Maintaining muscle mass gets harder without strength training.",
  53: "Cardiovascular endurance continues to decrease.",
  54: "Vision problems such as presbyopia are common.",
  55: "Risk of diabetes and metabolic syndrome becomes more prominent.",
  56: "Hormonal shifts drive further muscle and collagen loss.",
  57: "Risk of Alzheimer's disease and other cognitive disorders rises.",
  58: "Liver function declines slightly, affecting alcohol metabolism.",
  59: "Exercise recovery often becomes significantly slower.",
  60: "Loss of balance and coordination raises fall risk.",
  61: "Hearing loss becomes more pronounced.",
  62: "Metabolism slows significantly and weight gain becomes easier.",
  63: "Dependence on medication for chronic conditions often increases.",
  64: "Tendons stiffen and flexibility drops further.",
  65: "Immune response slows and infection risk rises.",
  66: "Muscle coordination declines and reaction times continue slowing.",
  67: "Fracture risk after falls becomes more serious.",
  68: "Cardiovascular efficiency declines markedly.",
  69: "Deep sleep shortens and sleep disruption becomes more common.",
  70: "Risk of neurodegenerative disease becomes substantially higher.",
  71: "Lean body mass declines significantly.",
  72: "Memory retention and processing speed continue to fall.",
  73: "Risk of heart disease and stroke remains high.",
  74: "Skin becomes thinner and bruising becomes easier.",
  75: "Physical endurance drops more sharply.",
  76: "Reliance on mobility aids becomes more common.",
  77: "Digestive efficiency falls and nutrient absorption declines.",
  78: "Temperature regulation worsens and cold sensitivity rises.",
  79: "Chronic pain becomes more common.",
  80: "Cognitive decline becomes more visible and dementia risk is high.",
  81: "Frailty increases and walking speed slows.",
  82: "A weaker immune system makes infection more dangerous.",
  83: "Swallowing difficulties may begin to appear.",
  84: "Muscle atrophy accelerates and limits mobility.",
  85: "Daily life often depends more heavily on caregivers.",
  86: "Bones become extremely fragile and fractures can be life-threatening.",
  87: "Loss of height from spinal compression becomes more evident.",
  88: "Risk of pneumonia and respiratory problems rises.",
  89: "Nerve function declines and sensitivity in the limbs drops.",
  90: "Loss of independence in daily life becomes severe.",
  91: "Cardiac output falls significantly and fatigue comes faster.",
  92: "Memory recall declines sharply.",
  93: "Mobility often depends on assistive devices.",
  94: "Digestion slows dramatically and deficiency risk rises.",
  95: "Falls become very dangerous and often lead to serious injury.",
  96: "Body composition shifts further toward frailty.",
  97: "Respiratory function becomes severely compromised.",
  98: "Hearing and vision loss become severe.",
  99: "Brain function is substantially impaired for many people.",
  100: "Mobility is highly limited and full-time care is often needed.",
  101: "Living past 100 remains rare, though some people stay independent.",
  102: "Extreme longevity often requires specialized care.",
  103: "Body mass declines further and bones become extremely fragile.",
  104: "Cognitive outcome depends heavily on genetics and overall health.",
  105: "Cardiovascular efficiency barely supports routine activity.",
  106: "Nutrient absorption becomes highly inefficient.",
  107: "Even minor illness can become a major threat.",
  108: "Severe muscle degeneration can lead to near-total immobility.",
  109: "Sensory perception may be almost completely lost.",
  110: "People who reach this age usually rely fully on caregivers.",
  111: "Mental function can fluctuate substantially.",
  112: "Heart function barely sustains the body's needs.",
  113: "Muscle control is almost entirely lost.",
  114: "Frailty becomes extreme and bones grow glasslike in fragility.",
  115: "Only a tiny number of people worldwide reach this age.",
  116: "Severe memory loss and cognitive decline are common.",
  117: "Dependence on life-support technology becomes more likely.",
  118: "The body struggles to maintain basic homeostasis.",
  119: "Cases are extremely rare, though exceptional longevity remains possible.",
  120: "Reaching this age is an extraordinary rarity.",
};

function translateFacts(transform) {
  return Object.fromEntries(
    Object.entries(englishFacts).map(([age, fact]) => [age, transform(fact, Number(age))])
  );
}

const bodyDevelopmentFactsByLocale = {
  en: englishFacts,
  zh: {
    0: "新生儿平均体重约 3.2 kg，头围接近 35 cm。",
    1: "乳牙开始萌出，学走路开始出现，大脑约达到成人体积的 60%。",
    2: "语言能力快速发展，脑内突触密度处于很高水平。",
    3: "免疫系统继续成熟，动作协调能力明显提升。",
    4: "乳牙基本长齐，视力已接近成人水平。",
    5: "体力增强，骨骼继续快速生长。",
    6: "第一恒磨牙出现，认知能力继续扩展。",
    7: "逻辑推理与手眼协调能力继续提高。",
    8: "生长速度略放缓，但精细动作能力仍在发展。",
    9: "记忆、专注和复杂肌肉协调能力进一步提升。",
    10: "大脑接近成人体积的 90%，认知持续精细化。",
    11: "部分儿童进入 puberty，激素分泌开始增加。",
    12: "骨骼生长加快，肌肉量增加。",
    13: "许多女孩进入身高增长高峰期，部分男孩开始变声。",
    14: "肺活量上升，运动表现通常进一步改善。",
    15: "许多男孩进入身高增长高峰期，肌肉力量继续增强。",
    16: "反应速度接近峰值，心肺耐力表现较强。",
    17: "骨密度继续增强，推理能力更趋稳定。",
    18: "大多数器官已基本发育成熟，皮肤韧性较好。",
    19: "代谢开始轻微放缓，但恢复能力通常仍然很快。",
    20: "力量与耐力等身体表现通常接近峰值。",
    21: "大脑发育趋于完全成熟，决策能力更稳定。",
    22: "肺功能与心血管效率通常接近最佳状态。",
    23: "骨量峰值通常在这一阶段形成，肌肉仍然强健。",
    24: "反应速度与敏捷性常处于很高水平。",
    25: "前额叶皮层已完全成熟，认知清晰度较高。",
    26: "肌腱与韧带弹性开始缓慢下降。",
    27: "如果缺乏训练，有氧能力会开始缓慢下滑。",
    28: "力量依旧较强，但恢复时间可能略有变长。",
    29: "高强度身体表现仍接近巅峰。",
    30: "代谢开始变慢，维持肌肉量变得更重要。",
    31: "胶原蛋白生成减少，皮肤老化早期迹象出现。",
    32: "耐力仍然较好，但峰值力量会略微下滑。",
    33: "心血管效率开始逐步下降。",
    34: "柔韧性下降，如果缺乏保养，受伤风险会提高。",
    35: "认知速度与记忆可能开始缓慢下降。",
    36: "若没有规律抗阻训练，肌肉流失开始出现。",
    37: "高强度活动后的恢复时间变长。",
    38: "关节僵硬感变得更明显。",
    39: "年龄相关视力下降的早期迹象更常见。",
    40: "若缺乏运动，肌肉流失加快，代谢进一步下降。",
    41: "高血压和胆固醇异常风险上升。",
    42: "反应速度放慢，耐力更依赖训练维持。",
    43: "皮肤弹性下降，皱纹更明显。",
    44: "部分人开始出现听力下降。",
    45: "心脏病风险增加，骨密度开始下降。",
    46: "激素变化可能带来肌肉流失和脂肪增加。",
    47: "骨质疏松风险升高，关节软骨逐渐磨损。",
    48: "免疫功能略有减弱，感染风险增加。",
    49: "记忆提取速度和信息处理速度可能下降。",
    50: "许多女性进入 menopause，骨密度流失加速。",
    51: "关节炎更常见，关节疼痛增加。",
    52: "如果缺乏力量训练，维持肌肉量会更困难。",
    53: "心血管耐力继续下降。",
    54: "老花等视力问题变得常见。",
    55: "糖尿病和代谢综合征风险更加突出。",
    56: "激素变化进一步带来肌肉与胶原流失。",
    57: "阿尔茨海默病和其他认知障碍风险上升。",
    58: "肝功能轻微下降，酒精代谢能力减弱。",
    59: "运动后的恢复时间往往明显变长。",
    60: "平衡与协调能力下降，跌倒风险上升。",
    61: "听力下降变得更明显。",
    62: "代谢明显放慢，更容易体重增加。",
    63: "对慢性病药物的依赖往往增加。",
    64: "肌腱更僵硬，柔韧性进一步下降。",
    65: "免疫反应减慢，感染风险上升。",
    66: "肌肉协调能力下降，反应时间继续放慢。",
    67: "跌倒后发生骨折的风险更高且更严重。",
    68: "心血管效率出现明显下降。",
    69: "深睡眠时间缩短，睡眠中断更常见。",
    70: "神经退行性疾病风险明显提高。",
    71: "瘦体重显著下降。",
    72: "记忆保持和信息处理速度继续下降。",
    73: "心脏病和中风风险仍处高位。",
    74: "皮肤变薄，更容易出现淤青。",
    75: "身体耐力下降更加明显。",
    76: "对助行器具的依赖更常见。",
    77: "消化效率下降，营养吸收变差。",
    78: "体温调节能力变差，对寒冷更敏感。",
    79: "慢性疼痛变得更常见。",
    80: "认知下降更易察觉，dementia 风险较高。",
    81: "虚弱程度增加，步行速度进一步下降。",
    82: "免疫系统减弱使感染更危险。",
    83: "可能开始出现吞咽困难。",
    84: "肌肉萎缩加速，活动能力进一步受限。",
    85: "日常生活往往更依赖照护者。",
    86: "骨骼极为脆弱，骨折可能带来生命危险。",
    87: "脊柱压缩带来的身高变矮更明显。",
    88: "肺炎和呼吸系统问题风险上升。",
    89: "神经功能下降，四肢感觉敏感度减弱。",
    90: "日常生活独立性严重下降。",
    91: "心输出量显著降低，疲劳来得更快。",
    92: "记忆提取能力明显减弱。",
    93: "行动能力常依赖辅助设备。",
    94: "消化明显放慢，营养缺乏风险增加。",
    95: "跌倒变得非常危险，往往导致严重损伤。",
    96: "身体组成进一步朝虚弱化发展。",
    97: "呼吸功能严重受限。",
    98: "听力和视力损失都变得非常严重。",
    99: "对许多人而言，大脑功能已明显受损。",
    100: "行动能力非常有限，往往需要全天照护。",
    101: "活过 100 岁仍然罕见，不过少数人仍能保持一定独立性。",
    102: "极端长寿通常需要更专业的照护支持。",
    103: "体重继续下降，骨骼变得极为脆弱。",
    104: "认知状态很大程度受遗传与整体健康影响。",
    105: "心血管效率仅勉强支持日常活动。",
    106: "营养吸收变得非常低效。",
    107: "即便轻微疾病也可能构成重大威胁。",
    108: "严重肌肉退化可导致接近完全失去行动能力。",
    109: "感官知觉可能接近完全丧失。",
    110: "达到这个年龄的人通常几乎完全依赖照护者。",
    111: "精神功能可能出现明显波动。",
    112: "心脏功能仅勉强维持身体基本需求。",
    113: "肌肉控制能力几乎完全丧失。",
    114: "虚弱达到极端水平，骨骼脆得像玻璃。",
    115: "全球能活到这个年龄的人极少。",
    116: "严重记忆丧失和认知下降十分常见。",
    117: "对生命支持技术的依赖概率更高。",
    118: "身体维持基本 homeostasis 都变得困难。",
    119: "真实案例极其罕见，但极端长寿仍非绝对不可能。",
    120: "活到这个年龄极其罕见。",
  },
  fr: translateFacts((fact, age) => {
    const custom = {
      0: "Les nouveau-nés pèsent en moyenne environ 3,2 kg, avec un périmètre crânien proche de 35 cm.",
      20: "Les performances physiques sont souvent proches du pic pour l'endurance et la force.",
      30: "Le métabolisme ralentit et préserver la masse musculaire devient plus important.",
      40: "La perte musculaire s'accélère sans exercice et le métabolisme ralentit davantage.",
      50: "La ménopause survient pour beaucoup de femmes et la perte osseuse accélère.",
      60: "La perte d'équilibre et de coordination augmente le risque de chute.",
      70: "Le risque de maladie neurodégénérative devient nettement plus élevé.",
      80: "Le déclin cognitif devient plus visible et le risque de démence est élevé.",
      100: "La mobilité est très limitée et une aide continue est souvent nécessaire.",
      120: "Atteindre cet âge reste une rareté extraordinaire.",
    };
    if (custom[age]) {
      return custom[age];
    }
    return `À ${age} ans : ${fact}`;
  }),
  ja: translateFacts((fact, age) => {
    const custom = {
      0: "新生児の平均体重は約 3.2 kg、頭囲は約 35 cm。",
      20: "持久力と筋力の両面で身体能力が高い時期にあることが多い。",
      30: "代謝が落ち始め、筋肉量の維持がより重要になる。",
      40: "運動しなければ筋肉減少が加速し、代謝もさらに低下する。",
      50: "多くの女性で menopause が起こり、骨密度低下が加速する。",
      60: "バランスと協調性の低下で転倒リスクが上がる。",
      70: "神経変性疾患のリスクがかなり高まる。",
      80: "認知低下がより目立ち、dementia のリスクが高い。",
      100: "可動性は大きく制限され、常時介護が必要なことが多い。",
      120: "この年齢に到達するのはきわめてまれである。",
    };
    if (custom[age]) {
      return custom[age];
    }
    return `${age}歳: ${fact}`;
  }),
  es: translateFacts((fact, age) => {
    const custom = {
      0: "Los recién nacidos pesan en promedio unos 3,2 kg y tienen un perímetro craneal cercano a 35 cm.",
      20: "El rendimiento físico suele estar cerca del máximo en fuerza y resistencia.",
      30: "El metabolismo se ralentiza y conservar masa muscular se vuelve más importante.",
      40: "La pérdida muscular se acelera sin ejercicio y el metabolismo sigue bajando.",
      50: "La menopausia llega para muchas mujeres y la pérdida ósea se acelera.",
      60: "La pérdida de equilibrio y coordinación eleva el riesgo de caídas.",
      70: "El riesgo de enfermedad neurodegenerativa aumenta de forma notable.",
      80: "El deterioro cognitivo se hace más visible y el riesgo de demencia es alto.",
      100: "La movilidad es muy limitada y a menudo se necesita cuidado continuo.",
      120: "Alcanzar esta edad es extraordinariamente raro.",
    };
    if (custom[age]) {
      return custom[age];
    }
    return `A los ${age}: ${fact}`;
  }),
};

export function getBodyDevelopmentFacts(locale) {
  return bodyDevelopmentFactsByLocale[normalizeLocale(locale)] || bodyDevelopmentFactsByLocale.en;
}

export default bodyDevelopmentFactsByLocale;
