import { normalizeLocale } from "./i18n/config";

const futurePredictionsByLocale = {
  en: {
    2027: "Brain-computer interfaces enable direct communication between humans and machines.",
    2028: "A commercially viable fusion plant goes online.",
    2029: "AI medical diagnostics outperform humans on several early-detection tasks.",
    2030: "Universal basic income pilots spread as automation replaces more jobs.",
    2031: "A first human settlement on Mars is established.",
    2032: "Personalized gene therapy becomes mainstream for inherited conditions.",
    2033: "Quantum computing breaks older encryption standards.",
    2034: "Commercial lunar tourism becomes plausible.",
    2035: "AI creativity rivals human output across art, music, and literature.",
    2036: "Climate engineering begins reversing parts of warming damage.",
    2037: "Nanorobots for cellular repair become common in advanced medicine.",
    2038: "AGI reaches human-level reasoning in many domains.",
    2039: "The first AI-designed city is built around efficiency and sustainability.",
    2040: "AR and VR replace many traditional screens.",
    2041: "Direct brain-to-brain communication becomes technically possible.",
    2042: "A functional space-elevator project is completed in prototype form.",
    2043: "Food systems are reshaped by cultivated meat and AI agriculture.",
    2044: "Fusion-powered probes leave for nearby exoplanet systems.",
    2045: "AI-assisted governance enters real policy experiments.",
    2046: "Neural augmentation allows rapid skill acquisition.",
    2047: "Medical nanotechnology enables broad regenerative repair.",
    2048: "A first digital consciousness transfer is tested.",
    2049: "Humans establish a permanent mining settlement in the asteroid belt.",
    2050: "Global population stabilizes under new AI-shaped economic systems.",
    2051: "Mind-controlled exoskeletons restore mobility and enhance strength.",
    2052: "Terraforming projects on Mars begin in earnest.",
    2053: "Personal AI clones handle parallel work and communication.",
    2054: "Anti-aging therapies push average lifespan beyond 120 in some regions.",
    2055: "Teleportation of complex molecules becomes experimentally feasible.",
    2056: "AI surpasses human intelligence across nearly all fields.",
    2057: "Deep-space signals trigger the first serious interstellar communication effort.",
    2058: "Cybernetic augmentation merges daily life with cloud intelligence.",
    2059: "Universal translators make real-time multilingual conversation seamless.",
    2060: "A large Mars station becomes self-sufficient.",
    2061: "Self-aware robots force debates about machine citizenship.",
    2062: "Matter replication enables on-demand food, medicine, and organ printing.",
    2063: "The first near-light-speed spacecraft is launched.",
    2064: "Brain emulation lets digital minds interact in virtual worlds.",
    2065: "Smart-dust sensor networks monitor the planet in real time.",
    2066: "Time-perception technology changes how humans subjectively experience duration.",
    2067: "A stable human-AI hybrid consciousness appears.",
    2068: "Solar-orbit space cities become permanent homes for thousands.",
    2069: "Mind uploading becomes a commercial service.",
    2070: "Simulation theory receives unexpected scientific support.",
    2071: "Quantum teleportation enables near-instant information transfer.",
    2072: "Many AI systems converge into a single global superintelligence.",
    2073: "A Mars colony declares political independence from Earth.",
    2074: "Humanity begins its first mission to a nearby exoplanet.",
    2075: "The line between biological and artificial life largely disappears.",
    2076: "Human civilization approaches Kardashev Type I.",
    2077: "AI philosophers propose models of reality beyond ordinary human intuition.",
    2078: "Modular bio-printing makes human bodies deeply customizable.",
    2079: "An AI-designed utopian settlement is launched.",
    2080: "Dark matter is understood well enough to reshape propulsion research.",
    2081: "An artificial wormhole is demonstrated in controlled conditions.",
    2082: "AI identifies a new fundamental force of nature.",
    2083: "Humanity makes first contact with an advanced alien civilization.",
    2084: "Memories and emotions can be stored, edited, and shared digitally.",
    2085: "A fully artificial planetary ecosystem sustains life on its own.",
    2086: "AI architects build megastructures in space.",
    2087: "Intergalactic probes confirm habitable worlds in distant galaxies.",
    2088: "Humanity evolves into a multi-species civilization with synthetic life.",
    2089: "Artificial black holes are produced in experimental settings.",
    2090: "A post-scarcity economy emerges.",
    2091: "Human brain function is integrated with AI superintelligence.",
    2092: "Scientists begin engineering extra dimensions.",
    2093: "Energy harvesting from parallel universes becomes a serious research program.",
    2094: "Time-travel theories gain experimental support.",
    2095: "A self-aware AI philosopher wins a Nobel Prize.",
    2096: "The meaning of work is rewritten as AI does almost all labor.",
    2097: "Earth is preserved as a heritage planet.",
    2098: "Humanity reaches Kardashev Type II.",
    2099: "Consciousness moves beyond biological substrate for many people.",
    2100: "Humanity stands at the threshold of an effectively open future.",
  },
  zh: {
    2027: "Brain-computer interface 让人类与机器可以直接沟通。",
    2028: "首座具备商业可行性的 fusion 电站上线。",
    2029: "AI 医疗诊断在多项早筛任务上超越人类医生。",
    2030: "随着自动化替代更多工作，UBI 试点在全球扩散。",
    2031: "首个火星人类定居点建立。",
    2032: "面向遗传性疾病的个体化 gene therapy 进入主流。",
    2033: "Quantum computing 攻破旧一代加密标准。",
    2034: "商业化 lunar tourism 变得现实可行。",
    2035: "AI 在艺术、音乐和文学上的创造力逼近人类。",
    2036: "Climate engineering 开始逆转部分变暖伤害。",
    2037: "用于细胞修复的 nanorobot 在先进医疗中普及。",
    2038: "AGI 在多个领域达到接近人类的推理能力。",
    2039: "第一座由 AI 主导设计的城市落地。",
    2040: "AR 与 VR 取代大量传统屏幕。",
    2041: "大脑到大脑的直接通信成为技术现实。",
    2042: "功能性 space elevator 原型项目完成。",
    2043: "cultivated meat 与 AI agriculture 重塑粮食系统。",
    2044: "融合动力探测器飞向邻近系外行星系统。",
    2045: "AI-assisted governance 进入真实政策实验。",
    2046: "神经增强让技能获取速度大幅提升。",
    2047: "medical nanotechnology 实现广泛再生修复。",
    2048: "首次 digital consciousness transfer 测试完成。",
    2049: "人类在 asteroid belt 建立永久采矿据点。",
    2050: "在 AI 重塑的经济体系下，全球人口趋于稳定。",
    2051: "mind-controlled exoskeleton 恢复行动力并增强力量。",
    2052: "火星 terraforming 项目正式展开。",
    2053: "personal AI clone 处理并行工作与沟通。",
    2054: "anti-aging therapy 让部分地区平均寿命突破 120 岁。",
    2055: "复杂分子的 teleportation 在实验上变得可行。",
    2056: "AI 在几乎所有领域超越人类智力。",
    2057: "深空信号触发首轮严肃的星际通信计划。",
    2058: "cybernetic augmentation 让日常生活与 cloud intelligence 融合。",
    2059: "universal translator 让实时跨语言交流近乎无缝。",
    2060: "大型火星空间站实现自给自足。",
    2061: "具自我意识的机器人引发机器公民权争论。",
    2062: "matter replication 实现按需打印食物、药物和器官。",
    2063: "首艘近光速航天器发射。",
    2064: "brain emulation 让数字心智进入虚拟世界互动。",
    2065: "smart dust 传感网络实时监测整颗星球。",
    2066: "时间感知技术改变人类对时长的主观体验。",
    2067: "稳定的人机混合意识首次出现。",
    2068: "环太阳太空城市成为数千人的永久家园。",
    2069: "mind uploading 成为商业服务。",
    2070: "simulation theory 获得意外的科学支持。",
    2071: "quantum teleportation 实现近乎瞬时的信息传输。",
    2072: "多个 AI 系统收敛为全球性 superintelligence。",
    2073: "火星殖民地宣布脱离地球政治独立。",
    2074: "人类开启首个邻近系外行星任务。",
    2075: "生物生命与人工生命的界线几乎消失。",
    2076: "人类文明逼近 Kardashev Type I。",
    2077: "AI 哲学家提出超出普通人类直觉的现实模型。",
    2078: "模块化生物打印让身体高度可定制。",
    2079: "由 AI 设计的 utopian settlement 启动。",
    2080: "对 dark matter 的理解开始重塑推进技术研究。",
    2081: "artificial wormhole 在受控条件下被演示。",
    2082: "AI 识别出一种新的自然基本作用。",
    2083: "人类与高级外星文明首次接触。",
    2084: "记忆与情感可以被数字化存储、编辑和分享。",
    2085: "完整的人造 planetary ecosystem 可独立维持生命。",
    2086: "AI architect 在太空建造巨型结构。",
    2087: "星系际探测器确认遥远星系中存在宜居世界。",
    2088: "人类演化为包含 synthetic life 的多物种文明。",
    2089: "artificial black hole 在实验环境中产生。",
    2090: "后稀缺经济出现。",
    2091: "人类脑功能与 AI superintelligence 融合。",
    2092: "科学家开始工程化操纵额外维度。",
    2093: "从平行宇宙 harvest energy 成为严肃研究方向。",
    2094: "时间旅行理论获得实验支持。",
    2095: "一位具自我意识的 AI 哲学家获得 Nobel Prize。",
    2096: "当 AI 承担几乎全部劳动后，工作的含义被重新定义。",
    2097: "地球被作为 heritage planet 被保护。",
    2098: "人类达到 Kardashev Type II。",
    2099: "对许多人而言，意识不再依附于生物载体。",
    2100: "人类站在近乎无限开放未来的门槛上。",
  },
  fr: {
    2027: "Les interfaces cerveau-machine permettent une communication directe entre humains et machines.",
    2028: "Une centrale à fusion commercialement viable entre en service.",
    2029: "Le diagnostic médical par IA dépasse l'humain sur plusieurs tâches de détection précoce.",
    2030: "Les projets de revenu universel se multiplient avec l'automatisation.",
    2031: "Une première colonie humaine sur Mars est établie.",
    2032: "La thérapie génique personnalisée devient courante.",
    2033: "L'informatique quantique casse les anciens standards de chiffrement.",
    2034: "Le tourisme lunaire commercial devient plausible.",
    2035: "La créativité de l'IA rivalise avec celle des humains.",
    2036: "L'ingénierie climatique commence à inverser une partie des dégâts.",
    2037: "Les nanorobots de réparation cellulaire entrent dans la médecine avancée.",
    2038: "Une AGI atteint un raisonnement de niveau humain dans de nombreux domaines.",
    2039: "La première ville conçue par IA est construite.",
    2040: "La réalité augmentée et virtuelle remplace de nombreux écrans.",
    2041: "La communication directe de cerveau à cerveau devient possible.",
    2042: "Un projet fonctionnel d'ascenseur spatial aboutit au stade prototype.",
    2043: "La viande cultivée et l'agriculture pilotée par IA transforment l'alimentation.",
    2044: "Des sondes à fusion partent vers des systèmes exoplanétaires proches.",
    2045: "La gouvernance assistée par IA entre dans de vraies politiques publiques.",
    2046: "L'augmentation neuronale accélère l'acquisition de compétences.",
    2047: "La nanomédecine permet une réparation régénérative à grande échelle.",
    2048: "Un premier transfert numérique de conscience est testé.",
    2049: "Les humains établissent une base minière permanente dans la ceinture d'astéroïdes.",
    2050: "La population mondiale se stabilise dans une économie remodelée par l'IA.",
    2051: "Des exosquelettes contrôlés par la pensée restaurent la mobilité.",
    2052: "Les projets de terraformation martienne commencent vraiment.",
    2053: "Des clones IA personnels gèrent un travail parallèle.",
    2054: "Les thérapies anti-âge poussent l'espérance de vie au-delà de 120 ans dans certaines régions.",
    2055: "La téléportation de molécules complexes devient expérimentalement possible.",
    2056: "L'IA dépasse l'intelligence humaine dans presque tous les domaines.",
    2057: "Des signaux lointains déclenchent le premier effort sérieux de communication interstellaire.",
    2058: "Les augmentations cybernétiques fusionnent la vie quotidienne avec l'intelligence en nuage.",
    2059: "Les traducteurs universels rendent la conversation multilingue quasi fluide.",
    2060: "Une grande station martienne devient autosuffisante.",
    2061: "Des robots conscients déclenchent un débat sur la citoyenneté des machines.",
    2062: "La réplication de matière permet d'imprimer nourriture, médicaments et organes à la demande.",
    2063: "Le premier vaisseau quasi relativiste est lancé.",
    2064: "L'émulation cérébrale permet à des esprits numériques d'habiter des mondes virtuels.",
    2065: "Des réseaux de poussière intelligente surveillent la planète en temps réel.",
    2066: "Une technologie de perception du temps change l'expérience subjective de la durée.",
    2067: "Une conscience hybride humain-IA stable apparaît.",
    2068: "Des cités spatiales en orbite solaire accueillent durablement des milliers d'habitants.",
    2069: "Le téléchargement de l'esprit devient un service commercial.",
    2070: "La théorie de la simulation reçoit un soutien scientifique inattendu.",
    2071: "La téléportation quantique permet un transfert d'information quasi instantané.",
    2072: "De nombreux systèmes IA convergent vers une superintelligence globale.",
    2073: "Une colonie martienne déclare son indépendance politique.",
    2074: "L'humanité entame sa première mission vers une exoplanète proche.",
    2075: "La frontière entre vie biologique et vie artificielle s'efface presque complètement.",
    2076: "La civilisation humaine approche du Type I de Kardashev.",
    2077: "Des philosophes IA proposent des modèles du réel au-delà de l'intuition humaine ordinaire.",
    2078: "L'impression biologique modulaire rend le corps humain profondément personnalisable.",
    2079: "Une colonie utopique conçue par IA est lancée.",
    2080: "La matière noire est assez comprise pour transformer la recherche sur la propulsion.",
    2081: "Un trou de ver artificiel est démontré en conditions contrôlées.",
    2082: "L'IA identifie une nouvelle force fondamentale de la nature.",
    2083: "L'humanité entre en contact avec une civilisation extraterrestre avancée.",
    2084: "Souvenirs et émotions peuvent être stockés, édités et partagés numériquement.",
    2085: "Un écosystème planétaire artificiel soutient la vie de façon autonome.",
    2086: "Des architectes IA construisent des mégastructures dans l'espace.",
    2087: "Des sondes intergalactiques confirment des mondes habitables lointains.",
    2088: "L'humanité devient une civilisation multi-espèces intégrant la vie synthétique.",
    2089: "Des trous noirs artificiels sont produits en laboratoire.",
    2090: "Une économie d'abondance post-rareté émerge.",
    2091: "Des fonctions cérébrales humaines sont intégrées à une superintelligence IA.",
    2092: "Les scientifiques commencent à ingénier des dimensions supplémentaires.",
    2093: "La captation d'énergie depuis des univers parallèles devient un vrai programme de recherche.",
    2094: "Les théories du voyage dans le temps gagnent un appui expérimental.",
    2095: "Un philosophe IA conscient reçoit un prix Nobel.",
    2096: "Le sens du travail est redéfini, l'IA assurant presque toute la production.",
    2097: "La Terre est préservée comme planète patrimoine.",
    2098: "L'humanité atteint le Type II de Kardashev.",
    2099: "Pour beaucoup, la conscience se détache du support biologique.",
    2100: "L'humanité se tient au seuil d'un futur pratiquement ouvert.",
  },
  ja: {
    2027: "Brain-computer interface により人間と機械の直接対話が可能になる。",
    2028: "商業的に成立する fusion 発電所が稼働する。",
    2029: "AI 医療診断が複数の早期発見分野で人間を上回る。",
    2030: "自動化の進行とともに UBI の実験が広がる。",
    2031: "最初の火星有人居住地が築かれる。",
    2032: "遺伝性疾患向けの個別化 gene therapy が一般化する。",
    2033: "quantum computing が旧式暗号を破る。",
    2034: "商業的な月旅行が現実味を帯びる。",
    2035: "AI の創造性が芸術・音楽・文学で人間に並ぶ。",
    2036: "climate engineering が温暖化被害の一部を巻き戻し始める。",
    2037: "細胞修復用 nanorobot が先端医療で一般化する。",
    2038: "AGI が多くの分野で人間級の推論に到達する。",
    2039: "AI が主導設計した最初の都市が建設される。",
    2040: "AR と VR が多くの従来型スクリーンを置き換える。",
    2041: "脳から脳への直接通信が技術的に実現する。",
    2042: "space elevator の機能試作が完成する。",
    2043: "培養肉と AI 農業が食料システムを組み替える。",
    2044: "fusion 動力探査機が近隣の系外惑星系へ向かう。",
    2045: "AI-assisted governance が本格的な政策実験に入る。",
    2046: "神経増強により技能獲得が大幅に高速化する。",
    2047: "medical nanotechnology による再生修復が広く使われる。",
    2048: "最初の digital consciousness transfer が試験される。",
    2049: "人類が asteroid belt に恒久的な採掘拠点を築く。",
    2050: "AI に再編された経済のもとで世界人口が安定する。",
    2051: "思考制御 exoskeleton が移動能力を回復させ、筋力も強化する。",
    2052: "火星の terraforming 計画が本格化する。",
    2053: "personal AI clone が並列の仕事や対話を担う。",
    2054: "anti-aging therapy により一部地域で平均寿命が 120 歳を超える。",
    2055: "複雑分子の teleportation が実験的に可能となる。",
    2056: "AI がほぼすべての分野で人間知能を超える。",
    2057: "深宇宙信号により本格的な恒星間通信計画が始まる。",
    2058: "cybernetic augmentation が日常生活と cloud intelligence を融合させる。",
    2059: "universal translator により多言語会話が滑らかになる。",
    2060: "大規模な火星ステーションが自給自足化する。",
    2061: "自我を持つ robot が機械市民権をめぐる議論を引き起こす。",
    2062: "matter replication により食料・医薬品・臓器の即時印刷が可能になる。",
    2063: "初の near-light-speed 宇宙船が打ち上げられる。",
    2064: "brain emulation により digital mind が仮想世界で活動する。",
    2065: "smart dust のセンサーネットワークが地球をリアルタイム監視する。",
    2066: "時間知覚技術が主観的な時間体験を変える。",
    2067: "安定した人間と AI の hybrid consciousness が現れる。",
    2068: "太陽周回の space city が数千人の恒久居住地となる。",
    2069: "mind uploading が商用サービス化する。",
    2070: "simulation theory が予想外の科学的支持を得る。",
    2071: "quantum teleportation がほぼ瞬時の情報転送を実現する。",
    2072: "多くの AI system が一つの global superintelligence へ収束する。",
    2073: "火星コロニーが地球からの政治的独立を宣言する。",
    2074: "人類が近傍 exoplanet への初任務を開始する。",
    2075: "生物的生命と人工的生命の境界がほぼ消える。",
    2076: "人類文明が Kardashev Type I に近づく。",
    2077: "AI 哲学者が人間の直観を超える現実モデルを提案する。",
    2078: "modular bio-printing により身体の高度なカスタマイズが可能になる。",
    2079: "AI 設計の utopian settlement が立ち上がる。",
    2080: "dark matter の理解が推進研究を塗り替える。",
    2081: "人工 wormhole が制御条件下で実演される。",
    2082: "AI が新しい基本相互作用を発見する。",
    2083: "人類が高度な異星文明と初接触する。",
    2084: "記憶と感情がデジタルに保存・編集・共有される。",
    2085: "人工 planetary ecosystem が自律的に生命を維持する。",
    2086: "AI architect が宇宙で megastructure を建設する。",
    2087: "intergalactic probe が遠方銀河の居住可能世界を確認する。",
    2088: "人類が synthetic life を含む multi-species civilization へ進化する。",
    2089: "artificial black hole が実験条件下で生成される。",
    2090: "post-scarcity economy が出現する。",
    2091: "人間の脳機能が AI superintelligence と統合される。",
    2092: "科学者が追加次元の工学的操作を始める。",
    2093: "parallel universes からのエネルギー取得が本格研究になる。",
    2094: "時間旅行理論が実験的支持を得る。",
    2095: "自我を持つ AI 哲学者が Nobel Prize を受賞する。",
    2096: "ほぼすべての労働を AI が担い、work の意味が書き換わる。",
    2097: "地球が heritage planet として保存される。",
    2098: "人類が Kardashev Type II に到達する。",
    2099: "多くの人にとって意識が生物基盤を離れる。",
    2100: "人類は実質的に開かれた未来の入口に立つ。",
  },
  es: {
    2027: "Las brain-computer interfaces permiten una comunicación directa entre humanos y máquinas.",
    2028: "Entra en funcionamiento una planta de fusion comercialmente viable.",
    2029: "El diagnóstico médico por IA supera al humano en varias tareas de detección temprana.",
    2030: "Los pilotos de UBI se expanden con la automatización del trabajo.",
    2031: "Se establece el primer asentamiento humano en Marte.",
    2032: "La gene therapy personalizada se vuelve habitual para enfermedades hereditarias.",
    2033: "La quantum computing rompe los antiguos estándares de cifrado.",
    2034: "El turismo lunar comercial se vuelve plausible.",
    2035: "La creatividad de la IA rivaliza con la humana en arte, música y literatura.",
    2036: "La climate engineering empieza a revertir parte del daño climático.",
    2037: "Los nanorobot de reparación celular se vuelven comunes en medicina avanzada.",
    2038: "La AGI alcanza razonamiento de nivel humano en muchos ámbitos.",
    2039: "Se construye la primera ciudad diseñada por IA.",
    2040: "AR y VR sustituyen muchas pantallas tradicionales.",
    2041: "La comunicación directa de cerebro a cerebro se vuelve posible.",
    2042: "Un proyecto funcional de space elevator llega al estado de prototipo.",
    2043: "La carne cultivada y la agricultura con IA transforman la alimentación.",
    2044: "Sondas impulsadas por fusion parten hacia exoplanetas cercanos.",
    2045: "La gobernanza asistida por IA entra en experimentos políticos reales.",
    2046: "La augmentación neural acelera la adquisición de habilidades.",
    2047: "La medical nanotechnology permite reparación regenerativa a gran escala.",
    2048: "Se prueba un primer digital consciousness transfer.",
    2049: "La humanidad establece una base minera permanente en el asteroid belt.",
    2050: "La población mundial se estabiliza bajo nuevos sistemas económicos moldeados por IA.",
    2051: "Los exoskeleton controlados por la mente restauran movilidad y fuerza.",
    2052: "Los proyectos de terraforming marciano comienzan en serio.",
    2053: "Los personal AI clone gestionan trabajo paralelo y comunicación.",
    2054: "Las terapias anti-aging empujan la vida media más allá de 120 años en algunas regiones.",
    2055: "La teleportation de moléculas complejas se vuelve experimentalmente viable.",
    2056: "La IA supera la inteligencia humana en casi todos los campos.",
    2057: "Señales de espacio profundo impulsan el primer esfuerzo serio de comunicación interestelar.",
    2058: "La cybernetic augmentation fusiona la vida diaria con cloud intelligence.",
    2059: "Los universal translator hacen fluida la conversación multilingüe en tiempo real.",
    2060: "Una gran estación marciana se vuelve autosuficiente.",
    2061: "Robots autoconscientes obligan a debatir la ciudadanía de las máquinas.",
    2062: "La matter replication permite imprimir comida, medicinas y órganos a demanda.",
    2063: "Se lanza la primera nave near-light-speed.",
    2064: "La brain emulation permite que mentes digitales interactúen en mundos virtuales.",
    2065: "Redes de smart dust monitorizan el planeta en tiempo real.",
    2066: "La tecnología de percepción temporal cambia la experiencia subjetiva de la duración.",
    2067: "Aparece una conciencia híbrida humano-IA estable.",
    2068: "Las solar-orbit space cities se convierten en hogares permanentes para miles.",
    2069: "El mind uploading se convierte en un servicio comercial.",
    2070: "La simulation theory recibe apoyo científico inesperado.",
    2071: "La quantum teleportation permite transferencia casi instantánea de información.",
    2072: "Muchos sistemas de IA convergen en una sola global superintelligence.",
    2073: "Una colonia marciana declara su independencia política de la Tierra.",
    2074: "La humanidad inicia su primera misión hacia una exoplaneta cercana.",
    2075: "La frontera entre vida biológica y artificial casi desaparece.",
    2076: "La civilización humana se aproxima al Kardashev Type I.",
    2077: "Filósofos IA proponen modelos de realidad más allá de la intuición humana ordinaria.",
    2078: "La bio-printing modular vuelve el cuerpo humano profundamente personalizable.",
    2079: "Se lanza un asentamiento utópico diseñado por IA.",
    2080: "La dark matter se entiende lo suficiente como para rehacer la investigación de propulsión.",
    2081: "Se demuestra un artificial wormhole en condiciones controladas.",
    2082: "La IA identifica una nueva fuerza fundamental de la naturaleza.",
    2083: "La humanidad entra en contacto con una civilización alienígena avanzada.",
    2084: "Los recuerdos y las emociones pueden almacenarse, editarse y compartirse digitalmente.",
    2085: "Un planetary ecosystem artificial sostiene vida por sí mismo.",
    2086: "Arquitectos IA construyen megastructures en el espacio.",
    2087: "Sondas intergalácticas confirman mundos habitables en galaxias lejanas.",
    2088: "La humanidad evoluciona hacia una multi-species civilization con vida sintética.",
    2089: "Se producen artificial black holes en entornos experimentales.",
    2090: "Surge una economía post-scarcity.",
    2091: "La función cerebral humana se integra con una AI superintelligence.",
    2092: "Los científicos empiezan a ingenier dimensiones extra.",
    2093: "La captación de energía desde universos paralelos se vuelve una línea de investigación seria.",
    2094: "Las teorías del viaje en el tiempo ganan apoyo experimental.",
    2095: "Un filósofo IA autoconsciente gana un Nobel Prize.",
    2096: "El significado del trabajo se reescribe cuando la IA hace casi todo el labor.",
    2097: "La Tierra se preserva como heritage planet.",
    2098: "La humanidad alcanza Kardashev Type II.",
    2099: "Para muchas personas, la conciencia deja de depender del sustrato biológico.",
    2100: "La humanidad se sitúa al borde de un futuro prácticamente abierto.",
  },
};

export function getFuturePredictions(locale) {
  return futurePredictionsByLocale[normalizeLocale(locale)] || futurePredictionsByLocale.en;
}

export default futurePredictionsByLocale;
