import { normalizeLocale } from "./i18n/config";

const quotesByLocale = {
  en: [
    "\" Despair is as illusory as hope. \"",
    "\" Better to walk than curse the road. \"",
    "\" To live is to suffer, to survive is to find some meaning in the suffering. \"",
    "\" He who has a why to live for can bear almost any how. \"",
    "\" We are our choices. \"",
    "\" Man is not the lord of beings. Man is the shepherd of Being. \"",
    "\" There is no cure for birth and death, save to enjoy the interval. \"",
    "\" Real generosity toward the future lies in giving all to the present. \"",
    "\" To be is to be in time. \"",
    "\" Compare yourself to who you were yesterday, not to who someone else is today. \"",
    "\" We are always complaining that our days are few, and acting as though there would be no end to them. \"",
    "\" You will never live if you are looking for the meaning of life. \"",
    "\" Dwell on the beauty of life. Watch the stars, and see yourself running with them. \"",
    "\" Life can only be understood backwards; but it must be lived forwards. \"",
    "\" It is never too late to be what you might have been. \"",
    "\" You must live in the present, launch yourself on every wave, find your eternity in each moment. \"",
    "\" There are no facts, only interpretations. \"",
    "\" A wise man will make more opportunities than he finds. \"",
    "\" The future depends on what you do today. \"",
    "\" We forfeit three-fourths of ourselves in order to be like other people. \"",
    "\" Every man is born as many men and dies as a single one. \"",
    "\" The best way to find out if you can trust somebody is to trust them. \"",
    "\" You could leave life right now. Let that determine what you do and say and think. \"",
    "\" Life is what happens when you’re busy making other plans. \"",
    "\" Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. \"",
    "\" Your time is limited, so don’t waste it living someone else’s life. \"",
    "\" An idea that is not dangerous is unworthy of being called an idea at all. \"",
    "\" Sometimes people don't want to hear the truth because they don't want their illusions destroyed. \"",
  ],
  zh: [
    "\" 绝望和希望一样，都是幻象。\"",
    "\" 与其诅咒道路，不如迈步前行。\"",
    "\" 活着就是受苦，生存就是在苦难中找到某种意义。\"",
    "\" 知道为何而活的人，几乎能承受任何生活方式。\"",
    "\" 我们就是自己的选择。\"",
    "\" 人不是万物的主宰，人是存在的牧人。\"",
    "\" 生与死无药可治，唯一可做的是享受其间的片刻。\"",
    "\" 对未来真正的慷慨，是把一切献给当下。\"",
    "\" 存在，就是处在时间之中。\"",
    "\" 与昨天的自己比较，而不是与今天的别人比较。\"",
    "\" 我们总抱怨来日无多，却又活得仿佛不会结束。\"",
    "\" 如果你一直追问生命的意义，你反而永远不会真正活着。\"",
    "\" 凝望生命之美。看星辰，也看自己与它们一同奔跑。\"",
    "\" 生命只能回头理解，却必须向前活。\"",
    "\" 成为你本可以成为的人，永远不算太晚。\"",
    "\" 活在当下，把自己投入每一道浪里，在每个瞬间找到永恒。\"",
    "\" 没有事实，只有解释。\"",
    "\" 智者创造的机会，总比他遇到的更多。\"",
    "\" 未来取决于你今天做什么。\"",
    "\" 为了像别人，我们放弃了四分之三的自己。\"",
    "\" 每个人生来都是许多个自己，死去时才成为一个。\"",
    "\" 判断一个人能否信任，最好的方式就是先去信任。\"",
    "\" 你现在就可能离开这个世界。让这一点决定你的言行与思考。\"",
    "\" 当你忙着计划别的事情时，人生正在发生。\"",
    "\" 不要沉溺过去，不要空想未来，把心放在当下这一刻。\"",
    "\" 你的时间有限，不要浪费在过别人想要你过的人生上。\"",
    "\" 一个想法如果不危险，就不配叫真正的想法。\"",
    "\" 有时人们不愿听真话，只因为他们不想让幻觉破灭。\"",
  ],
  fr: [
    "\" Le désespoir est aussi illusoire que l’espoir. \"",
    "\" Mieux vaut marcher que maudire la route. \"",
    "\" Vivre, c’est souffrir ; survivre, c’est trouver un sens à cette souffrance. \"",
    "\" Celui qui a un pourquoi peut supporter presque n’importe quel comment. \"",
    "\" Nous sommes nos choix. \"",
    "\" L’homme n’est pas le seigneur des êtres. Il est le berger de l’Être. \"",
    "\" Il n’existe pas de remède à la naissance et à la mort, sinon de savourer l’intervalle. \"",
    "\" La véritable générosité envers l’avenir consiste à tout donner au présent. \"",
    "\" Être, c’est être dans le temps. \"",
    "\" Comparez-vous à celui que vous étiez hier, pas à quelqu’un d’autre aujourd’hui. \"",
    "\" Nous nous plaignons sans cesse que nos jours sont peu nombreux, tout en vivant comme s’ils n’avaient pas de fin. \"",
    "\" Vous ne vivrez jamais vraiment si vous cherchez le sens de la vie comme un objet à posséder. \"",
    "\" Méditez la beauté de la vie. Regardez les étoiles, et voyez-vous courir avec elles. \"",
    "\" La vie ne peut être comprise qu’en regardant en arrière ; mais elle doit être vécue en avant. \"",
    "\" Il n’est jamais trop tard pour devenir ce que vous auriez pu être. \"",
    "\" Vivez au présent, jetez-vous dans chaque vague, trouvez votre éternité dans chaque instant. \"",
    "\" Il n’y a pas de faits, seulement des interprétations. \"",
    "\" Le sage crée plus d’occasions qu’il n’en rencontre. \"",
    "\" L’avenir dépend de ce que vous faites aujourd’hui. \"",
    "\" Nous abandonnons les trois quarts de nous-mêmes pour ressembler aux autres. \"",
    "\" Chaque homme naît multiple et meurt enfin unifié. \"",
    "\" Le meilleur moyen de savoir si l’on peut faire confiance à quelqu’un, c’est de lui faire confiance. \"",
    "\" Vous pourriez quitter la vie à l’instant. Que cela décide de ce que vous faites, dites et pensez. \"",
    "\" La vie, c’est ce qui arrive pendant que vous êtes occupé à faire d’autres projets. \"",
    "\" Ne vous attardez pas sur le passé, ne rêvez pas du futur, concentrez votre esprit sur l’instant présent. \"",
    "\" Votre temps est limité ; ne le gaspillez pas à vivre la vie de quelqu’un d’autre. \"",
    "\" Une idée qui n’est pas dangereuse ne mérite pas d’être appelée une idée. \"",
    "\" Parfois, on ne veut pas entendre la vérité parce qu’on ne veut pas voir ses illusions détruites. \"",
  ],
  ja: [
    "\" 絶望は希望と同じくらい幻想だ。\"",
    "\" 道を呪うより、歩き出したほうがいい。\"",
    "\" 生きることは苦しむこと、生き延びることはその苦しみに意味を見いだすことだ。\"",
    "\" なぜ生きるかを知る者は、ほとんどどんな生き方にも耐えられる。\"",
    "\" 私たちは自分の選択そのものだ。\"",
    "\" 人間は存在者の主ではない。存在の牧者である。\"",
    "\" 生と死に治療法はない。ただそのあいだを味わうだけだ。\"",
    "\" 未来への真の寛大さとは、現在にすべてを注ぐことだ。\"",
    "\" 在るとは、時間のうちに在ることだ。\"",
    "\" 昨日の自分と比べよ。今日の誰かと比べるな。\"",
    "\" 私たちは日々の短さを嘆きながら、終わりが来ないかのように振る舞っている。\"",
    "\" 人生の意味ばかり探していては、あなたは決して本当に生きられない。\"",
    "\" 人生の美しさに思いを向けよ。星を見上げ、自分がそれらとともに走っている姿を見よ。\"",
    "\" 人生は振り返って初めて理解できる。しかし生きるのは前を向いてだ。\"",
    "\" なり得た自分になるのに、遅すぎることはない。\"",
    "\" 今を生き、あらゆる波に身を投じ、一瞬ごとに永遠を見つけよ。\"",
    "\" 事実はなく、解釈があるだけだ。\"",
    "\" 賢者は、出会うより多くの機会を自ら作る。\"",
    "\" 未来は、今日あなたが何をするかで決まる。\"",
    "\" 私たちは他人のようになるために、自分の四分の三を手放している。\"",
    "\" 人は多くの自分として生まれ、ひとりの自分として死ぬ。\"",
    "\" 誰かを信頼できるか確かめる最善の方法は、実際に信頼してみることだ。\"",
    "\" あなたは今この瞬間に人生を去るかもしれない。その事実に、行いと言葉と思考を決めさせよ。\"",
    "\" 人生とは、ほかの計画に気を取られているあいだに起こるものだ。\"",
    "\" 過去にとらわれず、未来を夢想しすぎず、心を今この瞬間に集中させよ。\"",
    "\" あなたの時間は限られている。だから他人の人生を生きて無駄にしてはならない。\"",
    "\" 危険を含まない考えは、考えと呼ぶに値しない。\"",
    "\" ときに人は真実を聞きたがらない。自分の幻想を壊されたくないからだ。\"",
  ],
  es: [
    "\" La desesperación es tan ilusoria como la esperanza. \"",
    "\" Mejor caminar que maldecir el camino. \"",
    "\" Vivir es sufrir; sobrevivir es encontrar algún sentido en ese sufrimiento. \"",
    "\" Quien tiene un porqué para vivir puede soportar casi cualquier cómo. \"",
    "\" Somos nuestras elecciones. \"",
    "\" El hombre no es el señor de los seres. Es el pastor del Ser. \"",
    "\" No hay cura para el nacimiento y la muerte, salvo disfrutar del intervalo. \"",
    "\" La verdadera generosidad hacia el futuro consiste en entregarlo todo al presente. \"",
    "\" Ser es estar en el tiempo. \"",
    "\" Compárate con quien eras ayer, no con quien alguien más es hoy. \"",
    "\" Siempre nos quejamos de que nuestros días son pocos, y aun así actuamos como si no fueran a terminar nunca. \"",
    "\" Nunca vivirás de verdad si estás obsesionado con encontrar el significado de la vida. \"",
    "\" Detente en la belleza de la vida. Mira las estrellas y mírate corriendo con ellas. \"",
    "\" La vida solo puede entenderse hacia atrás, pero debe vivirse hacia adelante. \"",
    "\" Nunca es demasiado tarde para ser quien podrías haber sido. \"",
    "\" Vive en el presente, lánzate a cada ola, encuentra tu eternidad en cada momento. \"",
    "\" No hay hechos, solo interpretaciones. \"",
    "\" Un hombre sabio crea más oportunidades de las que encuentra. \"",
    "\" El futuro depende de lo que hagas hoy. \"",
    "\" Renunciamos a tres cuartas partes de nosotros mismos para parecernos a los demás. \"",
    "\" Todo hombre nace como muchos y muere como uno solo. \"",
    "\" La mejor forma de saber si puedes confiar en alguien es confiar en él. \"",
    "\" Podrías abandonar la vida ahora mismo. Deja que eso decida lo que haces, dices y piensas. \"",
    "\" La vida es eso que sucede mientras estás ocupado haciendo otros planes. \"",
    "\" No te quedes en el pasado, no sueñes con el futuro, concentra tu mente en el momento presente. \"",
    "\" Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona. \"",
    "\" Una idea que no es peligrosa no merece llamarse idea. \"",
    "\" A veces la gente no quiere oír la verdad porque no quiere que sus ilusiones se destruyan. \"",
  ],
};

export function getQuotes(locale) {
  return quotesByLocale[normalizeLocale(locale)] || quotesByLocale.en;
}

export default quotesByLocale;
