import { normalizeLocale } from "./i18n/config";

const techEventsByLocale = {
  en: {
    1900: "Max Planck proposes quantum theory.",
    1901: "Guglielmo Marconi transmits the first transatlantic radio signal.",
    1902: "The Wright brothers move toward the first powered flight.",
    1903: "The Wright brothers achieve the first powered flight.",
    1904: "John Ambrose Fleming invents the vacuum tube.",
    1905: "Albert Einstein publishes the theory of special relativity.",
    1906: "Reginald Fessenden carries out an early radio broadcast.",
    1907: "Leo Baekeland invents Bakelite, the first synthetic plastic.",
    1908: "Ford introduces the Model T and transforms mass production.",
    1909: "Airplanes see their first military use.",
    1910: "Thomas Edison demonstrates talking motion pictures.",
    1911: "Superconductivity is discovered.",
    1912: "The sinking of the Titanic drives advances in maritime safety.",
    1913: "Henry Ford's assembly line accelerates industrial efficiency.",
    1914: "World War I begins and pushes military technology forward.",
    1915: "Einstein presents the general theory of relativity.",
    1916: "Tanks are used in warfare for the first time.",
    1917: "The Zimmermann Telegram marks a major moment in cryptanalysis.",
    1918: "The Spanish flu accelerates modern public-health responses.",
    1919: "Alcock and Brown complete the first non-stop transatlantic flight.",
    1920: "Arthur Eddington confirms Einstein's general relativity.",
    1921: "Insulin is discovered and changes diabetes treatment.",
    1922: "An early 3D movie is shown to the public.",
    1923: "Garrett Morgan patents the modern traffic signal.",
    1924: "Edwin Hubble shows that the universe extends beyond the Milky Way.",
    1925: "John Logie Baird demonstrates the first working television.",
    1926: "Robert Goddard launches the first liquid-fueled rocket.",
    1927: "The first transatlantic telephone call is completed.",
    1928: "Alexander Fleming discovers penicillin.",
    1929: "Fritz Pfleumer patents magnetic tape for sound recording.",
    1930: "Pluto is discovered.",
    1931: "Kurt Godel publishes the incompleteness theorems.",
    1932: "Carl Anderson discovers the positron.",
    1933: "FM radio is invented.",
    1934: "Nuclear fission is first theorized.",
    1935: "Radar technology advances rapidly.",
    1936: "Alan Turing formalizes the Turing machine.",
    1937: "An early jet engine is tested.",
    1938: "Nuclear fission is demonstrated experimentally.",
    1939: "World War II accelerates computing and rocketry.",
    1940: "Synthetic rubber is developed at scale.",
    1941: "Konrad Zuse's Z3 becomes an early programmable computer.",
    1942: "The first controlled nuclear chain reaction is achieved.",
    1943: "Colossus, an early programmable digital computer, is built.",
    1944: "Harvard Mark I is completed.",
    1945: "Atomic bombs are dropped on Hiroshima and Nagasaki.",
    1946: "ENIAC, the first general-purpose electronic computer, is completed.",
    1947: "The transistor is invented at Bell Labs.",
    1948: "Claude Shannon establishes modern information theory.",
    1949: "EDSAC runs as an early stored-program computer.",
    1950: "Alan Turing proposes the Turing Test.",
    1951: "UNIVAC I becomes the first commercial computer sold in the United States.",
    1952: "The first hydrogen bomb test takes place.",
    1953: "Watson and Crick describe the structure of DNA.",
    1954: "A nuclear power plant begins operation in the USSR.",
    1955: "Fiber optics begin entering communications research.",
    1956: "Artificial intelligence is formally named as a field.",
    1957: "Sputnik 1 becomes the first artificial satellite.",
    1958: "The integrated circuit is developed.",
    1959: "The first microchip is produced.",
    1960: "The laser is invented.",
    1961: "Yuri Gagarin becomes the first human in space.",
    1962: "Telstar, an early communication satellite, is launched.",
    1963: "Touch-tone telephones are introduced.",
    1964: "IBM releases the System/360 mainframe family.",
    1965: "Moore's Law is formulated.",
    1966: "Early AI systems demonstrate chess playing.",
    1967: "The first successful human heart transplant is performed.",
    1968: "Douglas Engelbart demonstrates the computer mouse.",
    1969: "ARPANET, precursor to the Internet, is launched.",
    1970: "Intel introduces the first commercial microprocessor.",
    1971: "The first email is sent.",
    1972: "The Magnavox Odyssey launches as the first home video-game console.",
    1973: "The first mobile phone call is made.",
    1974: "Ethernet is developed.",
    1975: "Microsoft is founded.",
    1976: "Apple is founded.",
    1977: "The Apple II helps define the personal computer era.",
    1978: "The first GPS satellite is launched.",
    1979: "Sony introduces the Walkman.",
    1980: "IBM unveils the PC platform that shapes office computing.",
    1981: "The first space shuttle flies.",
    1982: "The compact disc reaches the market.",
    1983: "The Internet adopts TCP/IP.",
    1984: "Apple launches the Macintosh.",
    1985: "Microsoft releases Windows 1.0.",
    1986: "Chernobyl pushes nuclear-safety reforms.",
    1987: "3D video-game design begins to move into the mainstream.",
    1988: "The Morris worm reveals the fragility of the early Internet.",
    1989: "Tim Berners-Lee invents the World Wide Web.",
    1990: "The Hubble Space Telescope is launched.",
    1991: "Linux is created.",
    1992: "The first text message is sent.",
    1993: "Mosaic popularizes the web browser.",
    1994: "Amazon is founded.",
    1995: "Java is released.",
    1996: "Deep Blue defeats a reigning human chess champion in a match.",
    1997: "Google is founded.",
    1998: "Consumer MP3 players begin to reshape portable music.",
    1999: "Wi-Fi is standardized.",
    2000: "The Human Genome Project completes its first draft.",
    2001: "Wikipedia launches.",
    2002: "A complete draft of the human genome is published.",
    2003: "Spirit and Opportunity launch the modern Mars rover era.",
    2004: "Facebook is founded and reshapes social media.",
    2005: "YouTube is launched and transforms online video.",
    2006: "Twitter popularizes real-time microblogging.",
    2007: "Apple introduces the first iPhone.",
    2008: "The first Android phone is released.",
    2009: "Bitcoin launches and begins the era of decentralized digital assets.",
    2010: "Apple introduces the iPad and defines the modern tablet market.",
    2011: "IBM Watson wins on Jeopardy and spotlights practical AI systems.",
    2012: "CERN announces the Higgs boson discovery.",
    2013: "CRISPR accelerates a new era of gene editing.",
    2014: "Tesla helps make electric vehicles a mainstream ambition.",
    2015: "AI defeats a professional Go player for the first time.",
    2016: "AlphaGo defeats Lee Sedol and marks a deep-learning milestone.",
    2017: "CRISPR is applied to viable human embryos in a landmark experiment.",
    2018: "Waymo launches an early commercial robotaxi service.",
    2019: "The Event Horizon Telescope captures the first image of a black hole.",
    2020: "OpenAI releases GPT-3 and expands the reach of large language models.",
    2021: "The James Webb Space Telescope is successfully launched.",
    2022: "Scientists announce a net-energy-gain fusion result.",
    2023: "Generative AI reaches the mainstream through tools like ChatGPT and Midjourney.",
    2024: "AI assistants become routine tools for writing, coding, search, and daily work.",
    2025: "AI agents move from answering to acting, while local AI computing matures.",
    2026: "Agentic coding enters the mainstream, with AI writing more code under human direction.",
  },
  zh: {
    1900: "马克斯·普朗克提出量子理论。",
    1901: "古列尔莫·马可尼完成首次跨大西洋无线电信号传输。",
    1902: "莱特兄弟继续逼近首次动力飞行。",
    1903: "莱特兄弟完成首次动力飞行。",
    1904: "约翰·安布罗斯·弗莱明发明真空管。",
    1905: "爱因斯坦发表狭义相对论。",
    1906: "雷金纳德·费森登完成早期无线电广播实验。",
    1907: "利奥·贝克兰发明第一种合成塑料 Bakelite。",
    1908: "福特推出 Model T，改写大规模生产方式。",
    1909: "飞机首次被用于军事场景。",
    1910: "爱迪生展示有声活动影像。",
    1911: "超导现象被发现。",
    1912: "泰坦尼克号沉没推动海事安全改进。",
    1913: "亨利·福特的装配线显著提升工业效率。",
    1914: "第一次世界大战爆发并推动军工技术发展。",
    1915: "爱因斯坦提出广义相对论。",
    1916: "坦克首次用于战争。",
    1917: "齐默尔曼电报成为密码分析的重要时刻。",
    1918: "西班牙流感加速了现代公共卫生响应。",
    1919: "阿尔科克与布朗完成首次不间断跨大西洋飞行。",
    1920: "阿瑟·爱丁顿验证广义相对论。",
    1921: "胰岛素被发现，彻底改变糖尿病治疗。",
    1922: "早期 3D 电影向公众放映。",
    1923: "加勒特·摩根为现代交通信号灯申请专利。",
    1924: "埃德温·哈勃证明宇宙远不止银河系。",
    1925: "约翰·洛吉·贝尔德演示第一台可用电视。",
    1926: "罗伯特·戈达德发射首枚液体燃料火箭。",
    1927: "首次跨大西洋电话通话完成。",
    1928: "亚历山大·弗莱明发现青霉素。",
    1929: "弗里茨·普弗卢默为磁带录音技术申请专利。",
    1930: "冥王星被发现。",
    1931: "库尔特·哥德尔发表不完备定理。",
    1932: "卡尔·安德森发现正电子。",
    1933: "FM 广播被发明。",
    1934: "核裂变首次被理论化描述。",
    1935: "雷达技术快速推进。",
    1936: "图灵形式化提出图灵机概念。",
    1937: "早期喷气发动机完成测试。",
    1938: "核裂变被实验性实现。",
    1939: "第二次世界大战加速了计算与火箭技术。",
    1940: "合成橡胶实现规模化发展。",
    1941: "康拉德·楚泽的 Z3 成为早期可编程计算机。",
    1942: "首次可控核链式反应实现。",
    1943: "早期可编程数字计算机 Colossus 建成。",
    1944: "Harvard Mark I 完成。",
    1945: "原子弹投向广岛与长崎。",
    1946: "第一台通用电子计算机 ENIAC 完成。",
    1947: "晶体管在贝尔实验室诞生。",
    1948: "香农建立现代信息论基础。",
    1949: "EDSAC 成为早期存储程序计算机。",
    1950: "图灵提出图灵测试。",
    1951: "UNIVAC I 成为在美国售出的首台商用计算机。",
    1952: "首次氢弹试验进行。",
    1953: "沃森与克里克揭示 DNA 结构。",
    1954: "苏联的核电站投入运行。",
    1955: "光纤开始进入通信研究。",
    1956: "Artificial Intelligence 被正式命名为一个领域。",
    1957: "Sputnik 1 成为第一颗人造卫星。",
    1958: "集成电路被开发出来。",
    1959: "首批 microchip 出现。",
    1960: "激光被发明。",
    1961: "尤里·加加林成为首位进入太空的人类。",
    1962: "早期通信卫星 Telstar 发射。",
    1963: "按键式电话进入市场。",
    1964: "IBM 发布 System/360 主机家族。",
    1965: "Moore's Law 被提出。",
    1966: "早期 AI 系统展示下棋能力。",
    1967: "首次成功的人类心脏移植完成。",
    1968: "道格拉斯·恩格尔巴特演示 computer mouse。",
    1969: "ARPANET 上线，成为 Internet 前身。",
    1970: "Intel 推出首个商用 microprocessor。",
    1971: "第一封 email 发出。",
    1972: "Magnavox Odyssey 作为首款家用游戏机发布。",
    1973: "第一次 mobile phone 通话完成。",
    1974: "Ethernet 被开发。",
    1975: "Microsoft 成立。",
    1976: "Apple 成立。",
    1977: "Apple II 帮助定义 personal computer 时代。",
    1978: "第一颗 GPS 卫星发射。",
    1979: "Sony 推出 Walkman。",
    1980: "IBM 推出 PC 平台，塑造办公计算格局。",
    1981: "第一架 Space Shuttle 飞行。",
    1982: "Compact Disc 进入市场。",
    1983: "Internet 采用 TCP/IP。",
    1984: "Apple 推出 Macintosh。",
    1985: "Microsoft 发布 Windows 1.0。",
    1986: "切尔诺贝利事故推动核安全改革。",
    1987: "3D 游戏设计开始走向主流。",
    1988: "Morris worm 暴露早期 Internet 的脆弱性。",
    1989: "蒂姆·伯纳斯-李发明 World Wide Web。",
    1990: "Hubble Space Telescope 发射。",
    1991: "Linux 诞生。",
    1992: "第一条 text message 发出。",
    1993: "Mosaic 推动 web browser 普及。",
    1994: "Amazon 成立。",
    1995: "Java 发布。",
    1996: "Deep Blue 在比赛中击败在位国际象棋冠军。",
    1997: "Google 成立。",
    1998: "消费级 MP3 player 开始改写便携音乐。",
    1999: "Wi‑Fi 标准化。",
    2000: "Human Genome Project 完成首版草图。",
    2001: "Wikipedia 上线。",
    2002: "完整的人类基因组草图发表。",
    2003: "Spirit 与 Opportunity 开启现代 Mars rover 时代。",
    2004: "Facebook 成立并重塑 social media。",
    2005: "YouTube 上线，改变 online video。",
    2006: "Twitter 让实时 microblogging 流行起来。",
    2007: "Apple 推出首款 iPhone。",
    2008: "首款 Android 手机发布。",
    2009: "Bitcoin 上线，开启去中心化数字资产时代。",
    2010: "Apple 推出 iPad，定义现代 tablet 市场。",
    2011: "IBM Watson 在 Jeopardy 上获胜，展示实用 AI。",
    2012: "CERN 宣布发现 Higgs boson。",
    2013: "CRISPR 推动 gene editing 进入新阶段。",
    2014: "Tesla 让 electric vehicle 成为主流野心。",
    2015: "AI 首次击败职业围棋棋手。",
    2016: "AlphaGo 战胜李世石，成为 deep learning 里程碑。",
    2017: "CRISPR 在可存活人类胚胎上的实验引发重大关注。",
    2018: "Waymo 启动早期 commercial robotaxi 服务。",
    2019: "Event Horizon Telescope 拍下首张 black hole 图像。",
    2020: "OpenAI 发布 GPT-3，扩大 large language model 的影响力。",
    2021: "James Webb Space Telescope 成功发射。",
    2022: "科学家宣布实现 net energy gain 的 fusion 结果。",
    2023: "生成式 AI 借由 ChatGPT 和 Midjourney 进入主流。",
    2024: "AI assistant 成为写作、coding、搜索与日常工作的常用工具。",
    2025: "AI agent 从回答走向执行，local AI computing 进一步成熟。",
    2026: "Agentic coding 进入主流，AI 在人类主导下写出更多代码。",
  },
  fr: {
    1900: "Max Planck propose la théorie quantique.",
    1901: "Guglielmo Marconi transmet le premier signal radio transatlantique.",
    1902: "Les frères Wright se rapprochent du premier vol motorisé.",
    1903: "Les frères Wright réalisent le premier vol motorisé.",
    1904: "John Ambrose Fleming invente la lampe à vide.",
    1905: "Albert Einstein publie la relativité restreinte.",
    1906: "Reginald Fessenden mène une des premières émissions radio.",
    1907: "Leo Baekeland invente la bakélite, premier plastique synthétique.",
    1908: "Ford lance la Model T et transforme la production de masse.",
    1909: "Les avions connaissent leur premier usage militaire.",
    1910: "Thomas Edison présente le cinéma parlant.",
    1911: "La supraconductivité est découverte.",
    1912: "Le naufrage du Titanic pousse les progrès de la sécurité maritime.",
    1913: "La chaîne de montage d'Henry Ford accélère l'efficacité industrielle.",
    1914: "La Première Guerre mondiale fait avancer les technologies militaires.",
    1915: "Einstein présente la relativité générale.",
    1916: "Les chars sont utilisés pour la première fois.",
    1917: "Le télégramme Zimmermann marque l'histoire de la cryptanalyse.",
    1918: "La grippe espagnole accélère les réponses modernes de santé publique.",
    1919: "Alcock et Brown réalisent le premier vol transatlantique sans escale.",
    1920: "Arthur Eddington confirme la relativité générale.",
    1921: "L'insuline est découverte et transforme le traitement du diabète.",
    1922: "Un des premiers films 3D est montré au public.",
    1923: "Garrett Morgan dépose le brevet du feu de signalisation moderne.",
    1924: "Edwin Hubble montre que l'univers dépasse la Voie lactée.",
    1925: "John Logie Baird démontre la première télévision fonctionnelle.",
    1926: "Robert Goddard lance la première fusée à ergols liquides.",
    1927: "Le premier appel téléphonique transatlantique est réalisé.",
    1928: "Alexander Fleming découvre la pénicilline.",
    1929: "Fritz Pfleumer brevète la bande magnétique.",
    1930: "Pluton est découverte.",
    1931: "Kurt Godel publie les théorèmes d'incomplétude.",
    1932: "Carl Anderson découvre le positron.",
    1933: "La radio FM est inventée.",
    1934: "La fission nucléaire est théorisée.",
    1935: "La technologie radar progresse rapidement.",
    1936: "Alan Turing formalise la machine de Turing.",
    1937: "Un des premiers moteurs à réaction est testé.",
    1938: "La fission nucléaire est démontrée expérimentalement.",
    1939: "La Seconde Guerre mondiale accélère l'informatique et la fuséologie.",
    1940: "Le caoutchouc synthétique se développe à grande échelle.",
    1941: "Le Z3 de Konrad Zuse devient un ordinateur programmable précoce.",
    1942: "La première réaction nucléaire en chaîne contrôlée est obtenue.",
    1943: "Colossus, ordinateur numérique programmable précoce, est construit.",
    1944: "Le Harvard Mark I est achevé.",
    1945: "Les bombes atomiques sont larguées sur Hiroshima et Nagasaki.",
    1946: "ENIAC, premier ordinateur électronique à usage général, est achevé.",
    1947: "Le transistor est inventé aux Bell Labs.",
    1948: "Claude Shannon fonde la théorie moderne de l'information.",
    1949: "EDSAC fonctionne comme un des premiers ordinateurs à programme enregistré.",
    1950: "Alan Turing propose le test de Turing.",
    1951: "UNIVAC I devient le premier ordinateur commercial vendu aux États-Unis.",
    1952: "Le premier essai de bombe H a lieu.",
    1953: "Watson et Crick décrivent la structure de l'ADN.",
    1954: "Une centrale nucléaire entre en service en URSS.",
    1955: "La fibre optique entre dans la recherche en communications.",
    1956: "L'intelligence artificielle est formellement nommée comme champ.",
    1957: "Sputnik 1 devient le premier satellite artificiel.",
    1958: "Le circuit intégré est développé.",
    1959: "La première puce électronique est produite.",
    1960: "Le laser est inventé.",
    1961: "Youri Gagarine devient le premier humain dans l'espace.",
    1962: "Telstar, satellite de communication précoce, est lancé.",
    1963: "Le téléphone à touches est introduit.",
    1964: "IBM lance la famille de mainframes System/360.",
    1965: "La loi de Moore est formulée.",
    1966: "Des systèmes d'IA précoces démontrent le jeu d'échecs.",
    1967: "La première transplantation cardiaque humaine réussie est réalisée.",
    1968: "Douglas Engelbart présente la souris informatique.",
    1969: "ARPANET, précurseur d'Internet, est lancé.",
    1970: "Intel introduit le premier microprocesseur commercial.",
    1971: "Le premier e-mail est envoyé.",
    1972: "La Magnavox Odyssey inaugure la console de salon.",
    1973: "Le premier appel sur téléphone mobile est passé.",
    1974: "Ethernet est développé.",
    1975: "Microsoft est fondée.",
    1976: "Apple est fondée.",
    1977: "L'Apple II aide à définir l'ère de l'ordinateur personnel.",
    1978: "Le premier satellite GPS est lancé.",
    1979: "Sony introduit le Walkman.",
    1980: "IBM dévoile la plateforme PC qui structure l'informatique de bureau.",
    1981: "La première navette spatiale décolle.",
    1982: "Le compact disc arrive sur le marché.",
    1983: "Internet adopte TCP/IP.",
    1984: "Apple lance le Macintosh.",
    1985: "Microsoft publie Windows 1.0.",
    1986: "Tchernobyl impose des réformes de sûreté nucléaire.",
    1987: "Le jeu vidéo 3D commence à entrer dans le courant dominant.",
    1988: "Le ver Morris révèle la fragilité de l'Internet précoce.",
    1989: "Tim Berners-Lee invente le World Wide Web.",
    1990: "Le télescope spatial Hubble est lancé.",
    1991: "Linux est créé.",
    1992: "Le premier SMS est envoyé.",
    1993: "Mosaic popularise le navigateur web.",
    1994: "Amazon est fondée.",
    1995: "Java est publié.",
    1996: "Deep Blue bat un champion d'échecs en titre dans un match.",
    1997: "Google est fondée.",
    1998: "Les lecteurs MP3 grand public commencent à transformer la musique portable.",
    1999: "Le Wi-Fi est normalisé.",
    2000: "Le Human Genome Project achève une première ébauche.",
    2001: "Wikipedia est lancée.",
    2002: "Une ébauche complète du génome humain est publiée.",
    2003: "Spirit et Opportunity ouvrent l'ère moderne des rovers martiens.",
    2004: "Facebook est fondée et redessine les réseaux sociaux.",
    2005: "YouTube est lancé et transforme la vidéo en ligne.",
    2006: "Twitter popularise le microblogging en temps réel.",
    2007: "Apple introduit le premier iPhone.",
    2008: "Le premier téléphone Android est lancé.",
    2009: "Bitcoin apparaît et ouvre l'ère des actifs numériques décentralisés.",
    2010: "Apple présente l'iPad et définit le marché moderne de la tablette.",
    2011: "IBM Watson gagne à Jeopardy et met l'IA pratique sous les projecteurs.",
    2012: "Le CERN annonce la découverte du boson de Higgs.",
    2013: "CRISPR accélère une nouvelle ère d'édition génétique.",
    2014: "Tesla contribue à faire du véhicule électrique une ambition grand public.",
    2015: "Une IA bat pour la première fois un joueur professionnel de Go.",
    2016: "AlphaGo bat Lee Sedol et marque un jalon du deep learning.",
    2017: "CRISPR est appliqué à des embryons humains viables dans une expérience marquante.",
    2018: "Waymo lance un service robotaxi commercial précoce.",
    2019: "L'Event Horizon Telescope capture la première image d'un trou noir.",
    2020: "OpenAI publie GPT-3 et élargit l'influence des grands modèles de langage.",
    2021: "Le télescope spatial James Webb est lancé avec succès.",
    2022: "Des scientifiques annoncent un résultat de fusion à gain net d'énergie.",
    2023: "L'IA générative entre dans le grand public via ChatGPT et Midjourney.",
    2024: "Les assistants IA deviennent des outils ordinaires pour écrire, coder, chercher et travailler.",
    2025: "Les agents IA passent de la réponse à l'action, tandis que l'IA locale progresse.",
    2026: "Le coding agentique entre dans le courant dominant, avec plus de code écrit par l'IA sous direction humaine.",
  },
  ja: {
    1900: "マックス・プランクが量子論を提案する。",
    1901: "グリエルモ・マルコーニが大西洋横断無線通信を実現する。",
    1902: "ライト兄弟が動力飛行直前まで到達する。",
    1903: "ライト兄弟が初の動力飛行に成功する。",
    1904: "ジョン・アンブローズ・フレミングが真空管を発明する。",
    1905: "アインシュタインが特殊相対性理論を発表する。",
    1906: "レジナルド・フェッセンデンが初期の無線放送を行う。",
    1907: "レオ・ベークランドが最初の合成樹脂ベークライトを発明する。",
    1908: "フォードが Model T を投入し、大量生産を変える。",
    1909: "飛行機が初めて軍事利用される。",
    1910: "エジソンがトーキー映像を実演する。",
    1911: "超伝導が発見される。",
    1912: "タイタニック号沈没が海上安全の改善を促す。",
    1913: "ヘンリー・フォードの組立ラインが工業効率を高める。",
    1914: "第一次世界大戦が始まり、軍事技術を押し上げる。",
    1915: "アインシュタインが一般相対性理論を提示する。",
    1916: "戦車が初めて実戦投入される。",
    1917: "ツィンメルマン電報が暗号解析史の重要事件となる。",
    1918: "スペインかぜが近代公衆衛生対応を加速させる。",
    1919: "アルコックとブラウンが初の無着陸大西洋横断飛行を達成する。",
    1920: "アーサー・エディントンが一般相対性理論を確認する。",
    1921: "インスリンが発見され、糖尿病治療を変える。",
    1922: "初期の 3D 映画が一般公開される。",
    1923: "ギャレット・モーガンが現代的な信号機の特許を取る。",
    1924: "エドウィン・ハッブルが宇宙が銀河系を超えて広がることを示す。",
    1925: "ジョン・ロジー・ベアードが実用的なテレビを実演する。",
    1926: "ロバート・ゴダードが液体燃料ロケットを打ち上げる。",
    1927: "初の大西洋横断電話通話が行われる。",
    1928: "アレクサンダー・フレミングがペニシリンを発見する。",
    1929: "フリッツ・プフロイマーが磁気テープを特許化する。",
    1930: "冥王星が発見される。",
    1931: "クルト・ゲーデルが不完全性定理を発表する。",
    1932: "カール・アンダーソンが陽電子を発見する。",
    1933: "FM ラジオが発明される。",
    1934: "核分裂が理論的に示される。",
    1935: "レーダー技術が急速に進展する。",
    1936: "アラン・チューリングがチューリングマシンを定式化する。",
    1937: "初期のジェットエンジンが試験される。",
    1938: "核分裂が実験的に実証される。",
    1939: "第二次世界大戦が計算技術とロケット開発を加速させる。",
    1940: "合成ゴムが大規模に開発される。",
    1941: "コンラート・ツーゼの Z3 が初期の programmable computer となる。",
    1942: "初の制御された核連鎖反応が達成される。",
    1943: "初期の programmable digital computer である Colossus が建造される。",
    1944: "Harvard Mark I が完成する。",
    1945: "広島と長崎に原子爆弾が投下される。",
    1946: "汎用電子計算機 ENIAC が完成する。",
    1947: "Bell Labs で transistor が発明される。",
    1948: "クロード・シャノンが現代情報理論の基礎を築く。",
    1949: "EDSAC が初期の stored-program computer として稼働する。",
    1950: "アラン・チューリングが Turing Test を提案する。",
    1951: "UNIVAC I が米国で販売された最初の商用 computer となる。",
    1952: "初の水爆実験が行われる。",
    1953: "ワトソンとクリックが DNA 構造を示す。",
    1954: "ソ連で原子力発電所が稼働する。",
    1955: "fiber optics が通信研究に入り始める。",
    1956: "Artificial Intelligence が正式な学問分野として名付けられる。",
    1957: "Sputnik 1 が最初の人工衛星となる。",
    1958: "integrated circuit が開発される。",
    1959: "最初の microchip が生産される。",
    1960: "laser が発明される。",
    1961: "ユーリイ・ガガーリンが人類初の宇宙飛行を達成する。",
    1962: "初期の通信衛星 Telstar が打ち上げられる。",
    1963: "プッシュホンが導入される。",
    1964: "IBM が System/360 を発表する。",
    1965: "Moore's Law が定式化される。",
    1966: "初期 AI がチェス能力を示す。",
    1967: "初の成功した心臓移植が行われる。",
    1968: "ダグラス・エンゲルバートが computer mouse を披露する。",
    1969: "Internet の前身 ARPANET が稼働する。",
    1970: "Intel が最初の商用 microprocessor を投入する。",
    1971: "最初の email が送られる。",
    1972: "Magnavox Odyssey が家庭用ゲーム機として登場する。",
    1973: "初の mobile phone 通話が行われる。",
    1974: "Ethernet が開発される。",
    1975: "Microsoft が創業される。",
    1976: "Apple が創業される。",
    1977: "Apple II が personal computer 時代を方向づける。",
    1978: "最初の GPS 衛星が打ち上げられる。",
    1979: "Sony が Walkman を発売する。",
    1980: "IBM が PC プラットフォームを打ち出し、オフィス computing を形づくる。",
    1981: "最初の Space Shuttle が飛行する。",
    1982: "Compact Disc が市場に出る。",
    1983: "Internet が TCP/IP を採用する。",
    1984: "Apple が Macintosh を発売する。",
    1985: "Microsoft が Windows 1.0 を公開する。",
    1986: "チェルノブイリ事故が原子力安全改革を促す。",
    1987: "3D ゲーム設計が主流へ入り始める。",
    1988: "Morris worm が初期 Internet の脆さを示す。",
    1989: "ティム・バーナーズ＝リーが World Wide Web を発明する。",
    1990: "Hubble Space Telescope が打ち上げられる。",
    1991: "Linux が生まれる。",
    1992: "最初の text message が送信される。",
    1993: "Mosaic が web browser を一般化する。",
    1994: "Amazon が創業される。",
    1995: "Java が公開される。",
    1996: "Deep Blue が現役チャンピオン級の棋士を対局で破る。",
    1997: "Google が創業される。",
    1998: "consumer MP3 player が携帯音楽を変え始める。",
    1999: "Wi‑Fi が標準化される。",
    2000: "Human Genome Project が最初のドラフトを完成させる。",
    2001: "Wikipedia が始まる。",
    2002: "人類ゲノムの完全ドラフトが公表される。",
    2003: "Spirit と Opportunity が現代 Mars rover 時代を開く。",
    2004: "Facebook が創業され、social media を塗り替える。",
    2005: "YouTube が登場し、online video を変える。",
    2006: "Twitter がリアルタイム microblogging を一般化する。",
    2007: "Apple が初代 iPhone を発表する。",
    2008: "最初の Android phone が発売される。",
    2009: "Bitcoin が始まり、分散型デジタル資産時代が動き出す。",
    2010: "Apple が iPad を発表し、現代 tablet 市場を定義する。",
    2011: "IBM Watson が Jeopardy で勝利し、実用 AI を印象づける。",
    2012: "CERN が Higgs boson の発見を発表する。",
    2013: "CRISPR が gene editing の新時代を加速させる。",
    2014: "Tesla が electric vehicle を主流の目標に近づける。",
    2015: "AI が初めてプロ棋士を破る。",
    2016: "AlphaGo が李世石に勝ち、deep learning の節目となる。",
    2017: "CRISPR が生存可能な人間胚に適用され、大きな節目となる。",
    2018: "Waymo が初期の commercial robotaxi サービスを始める。",
    2019: "Event Horizon Telescope が black hole の初画像を撮影する。",
    2020: "OpenAI が GPT-3 を公開し、large language model の影響を広げる。",
    2021: "James Webb Space Telescope が打ち上げに成功する。",
    2022: "科学者が net-energy-gain fusion の結果を発表する。",
    2023: "ChatGPT や Midjourney により生成 AI が一般層へ広がる。",
    2024: "AI assistant が writing、coding、search、日常業務の定番ツールになる。",
    2025: "AI agent が回答から実行へ進み、local AI computing も成熟する。",
    2026: "Agentic coding が主流化し、人間の指揮の下で AI がより多くのコードを書く。",
  },
  es: {
    1900: "Max Planck propone la teoría cuántica.",
    1901: "Guglielmo Marconi transmite la primera señal de radio transatlántica.",
    1902: "Los hermanos Wright se acercan al primer vuelo motorizado.",
    1903: "Los hermanos Wright logran el primer vuelo motorizado.",
    1904: "John Ambrose Fleming inventa la válvula de vacío.",
    1905: "Albert Einstein publica la relatividad especial.",
    1906: "Reginald Fessenden realiza una de las primeras emisiones de radio.",
    1907: "Leo Baekeland inventa la baquelita, el primer plástico sintético.",
    1908: "Ford presenta el Model T y transforma la producción en masa.",
    1909: "Los aviones tienen su primer uso militar.",
    1910: "Thomas Edison demuestra imágenes en movimiento con sonido.",
    1911: "Se descubre la superconductividad.",
    1912: "El hundimiento del Titanic impulsa avances en seguridad marítima.",
    1913: "La cadena de montaje de Henry Ford acelera la eficiencia industrial.",
    1914: "La Primera Guerra Mundial empuja la tecnología militar hacia adelante.",
    1915: "Einstein presenta la relatividad general.",
    1916: "Los tanques se usan por primera vez en combate.",
    1917: "El telegrama Zimmermann marca un momento clave de la criptoanálisis.",
    1918: "La gripe española acelera las respuestas modernas de salud pública.",
    1919: "Alcock y Brown completan el primer vuelo transatlántico sin escalas.",
    1920: "Arthur Eddington confirma la relatividad general.",
    1921: "Se descubre la insulina y cambia el tratamiento de la diabetes.",
    1922: "Una de las primeras películas en 3D se muestra al público.",
    1923: "Garrett Morgan patenta el semáforo moderno.",
    1924: "Edwin Hubble demuestra que el universo va más allá de la Vía Láctea.",
    1925: "John Logie Baird demuestra la primera televisión funcional.",
    1926: "Robert Goddard lanza el primer cohete de combustible líquido.",
    1927: "Se completa la primera llamada telefónica transatlántica.",
    1928: "Alexander Fleming descubre la penicilina.",
    1929: "Fritz Pfleumer patenta la cinta magnética.",
    1930: "Se descubre Plutón.",
    1931: "Kurt Godel publica los teoremas de incompletitud.",
    1932: "Carl Anderson descubre el positrón.",
    1933: "Se inventa la radio FM.",
    1934: "La fisión nuclear se teoriza por primera vez.",
    1935: "La tecnología radar avanza rápidamente.",
    1936: "Alan Turing formaliza la máquina de Turing.",
    1937: "Se prueba uno de los primeros motores a reacción.",
    1938: "La fisión nuclear se demuestra experimentalmente.",
    1939: "La Segunda Guerra Mundial acelera la computación y la cohetería.",
    1940: "El caucho sintético se desarrolla a gran escala.",
    1941: "El Z3 de Konrad Zuse se convierte en un ordenador programable temprano.",
    1942: "Se logra la primera reacción nuclear en cadena controlada.",
    1943: "Se construye Colossus, un ordenador digital programable temprano.",
    1944: "Se completa el Harvard Mark I.",
    1945: "Se lanzan bombas atómicas sobre Hiroshima y Nagasaki.",
    1946: "Se completa ENIAC, el primer ordenador electrónico de propósito general.",
    1947: "Se inventa el transistor en Bell Labs.",
    1948: "Claude Shannon funda la teoría moderna de la información.",
    1949: "EDSAC funciona como uno de los primeros ordenadores con programa almacenado.",
    1950: "Alan Turing propone la prueba de Turing.",
    1951: "UNIVAC I se convierte en el primer ordenador comercial vendido en Estados Unidos.",
    1952: "Tiene lugar la primera prueba de bomba de hidrógeno.",
    1953: "Watson y Crick describen la estructura del ADN.",
    1954: "Entra en funcionamiento una central nuclear en la URSS.",
    1955: "La fibra óptica entra en la investigación en comunicaciones.",
    1956: "La inteligencia artificial se nombra formalmente como campo.",
    1957: "Sputnik 1 se convierte en el primer satélite artificial.",
    1958: "Se desarrolla el circuito integrado.",
    1959: "Se produce el primer microchip.",
    1960: "Se inventa el láser.",
    1961: "Yuri Gagarin se convierte en el primer ser humano en el espacio.",
    1962: "Se lanza Telstar, uno de los primeros satélites de comunicaciones.",
    1963: "Se introducen los teléfonos de tonos.",
    1964: "IBM lanza la familia de mainframes System/360.",
    1965: "Se formula la ley de Moore.",
    1966: "Sistemas tempranos de IA muestran capacidad para jugar al ajedrez.",
    1967: "Se realiza el primer trasplante de corazón humano con éxito.",
    1968: "Douglas Engelbart presenta el ratón de ordenador.",
    1969: "Se lanza ARPANET, precursor de Internet.",
    1970: "Intel introduce el primer microprocesador comercial.",
    1971: "Se envía el primer correo electrónico.",
    1972: "Magnavox Odyssey inaugura la consola doméstica.",
    1973: "Se realiza la primera llamada por teléfono móvil.",
    1974: "Se desarrolla Ethernet.",
    1975: "Se funda Microsoft.",
    1976: "Se funda Apple.",
    1977: "El Apple II ayuda a definir la era del ordenador personal.",
    1978: "Se lanza el primer satélite GPS.",
    1979: "Sony presenta el Walkman.",
    1980: "IBM presenta la plataforma PC que da forma a la informática de oficina.",
    1981: "Vuela el primer transbordador espacial.",
    1982: "El compact disc llega al mercado.",
    1983: "Internet adopta TCP/IP.",
    1984: "Apple lanza el Macintosh.",
    1985: "Microsoft publica Windows 1.0.",
    1986: "Chernóbil impulsa reformas en seguridad nuclear.",
    1987: "El diseño de videojuegos 3D empieza a entrar en el mainstream.",
    1988: "El gusano Morris revela la fragilidad del Internet temprano.",
    1989: "Tim Berners-Lee inventa la World Wide Web.",
    1990: "Se lanza el telescopio espacial Hubble.",
    1991: "Se crea Linux.",
    1992: "Se envía el primer mensaje de texto.",
    1993: "Mosaic populariza el navegador web.",
    1994: "Se funda Amazon.",
    1995: "Se publica Java.",
    1996: "Deep Blue derrota en una partida a un campeón humano vigente.",
    1997: "Se funda Google.",
    1998: "Los reproductores MP3 de consumo empiezan a transformar la música portátil.",
    1999: "Se estandariza el Wi‑Fi.",
    2000: "El Human Genome Project completa su primer borrador.",
    2001: "Se lanza Wikipedia.",
    2002: "Se publica un borrador completo del genoma humano.",
    2003: "Spirit y Opportunity abren la era moderna de los rovers marcianos.",
    2004: "Se funda Facebook y remodela las redes sociales.",
    2005: "Se lanza YouTube y transforma el video en línea.",
    2006: "Twitter populariza el microblogging en tiempo real.",
    2007: "Apple presenta el primer iPhone.",
    2008: "Se lanza el primer teléfono Android.",
    2009: "Nace Bitcoin y comienza la era de los activos digitales descentralizados.",
    2010: "Apple presenta el iPad y define el mercado moderno de tablets.",
    2011: "IBM Watson gana en Jeopardy y muestra el potencial práctico de la IA.",
    2012: "CERN anuncia el descubrimiento del bosón de Higgs.",
    2013: "CRISPR acelera una nueva era de edición genética.",
    2014: "Tesla ayuda a convertir el vehículo eléctrico en una ambición masiva.",
    2015: "Una IA derrota por primera vez a un jugador profesional de Go.",
    2016: "AlphaGo derrota a Lee Sedol y marca un hito del deep learning.",
    2017: "CRISPR se aplica a embriones humanos viables en un experimento histórico.",
    2018: "Waymo lanza un servicio comercial temprano de robotaxi.",
    2019: "El Event Horizon Telescope captura la primera imagen de un agujero negro.",
    2020: "OpenAI publica GPT-3 y amplía el alcance de los grandes modelos de lenguaje.",
    2021: "Se lanza con éxito el telescopio espacial James Webb.",
    2022: "Científicos anuncian un resultado de fusión con ganancia neta de energía.",
    2023: "La IA generativa entra en el mainstream con ChatGPT y Midjourney.",
    2024: "Los asistentes de IA se vuelven herramientas habituales para escribir, programar, buscar y trabajar.",
    2025: "Los agentes de IA pasan de responder a actuar, mientras madura la IA local.",
    2026: "El agentic coding entra en el mainstream, con más código escrito por IA bajo dirección humana.",
  },
};

export function getTechEvents(locale) {
  return techEventsByLocale[normalizeLocale(locale)] || techEventsByLocale.en;
}

export default techEventsByLocale;
